version: "2"
run:
  tests: true
linters:
  enable:
    - dupl
    - err113
    - funlen
    - gochecknoinits
    - goconst
    - godot
    - godox
    - gomodguard_v2
    - goprintffuncname
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  disable:
    - depguard
    - exhaustive
    - gochecknoglobals
    - gocognit
    - gocritic
    - gocyclo
    - lll
    - nestif
    - nlreturn
    - testpackage
    - tparallel
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    funlen:
      lines: 100
      statements: 60
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable:
        - shadow
    lll:
      line-length: 120
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
    revive:
      confidence: 0.8
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gochecknoglobals
          - goconst
          - godot
          - mnd
          - wsl
        path: _test\.go
      - linters:
          - all
        path: vendor/
      - linters:
          - all
        path: internal/
    paths:
      - .*\.pb\.go$
      - internal
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/cyborginc/cyborgdb-go
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - internal
      - third_party$
      - builtin$
      - examples$
