/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cyborgdb

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteRequest{}

// DeleteRequest struct for DeleteRequest
type DeleteRequest struct {
	Ids []string `json:"ids"`
}

type _DeleteRequest DeleteRequest

// NewDeleteRequest instantiates a new DeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteRequest(ids []string) *DeleteRequest {
	this := DeleteRequest{}
	this.Ids = ids
	return &this
}

// NewDeleteRequestWithDefaults instantiates a new DeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteRequestWithDefaults() *DeleteRequest {
	this := DeleteRequest{}
	return &this
}

// GetIds returns the Ids field value
func (o *DeleteRequest) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *DeleteRequest) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *DeleteRequest) SetIds(v []string) {
	o.Ids = v
}

func (o DeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ids"] = o.Ids
	return toSerialize, nil
}

func (o *DeleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteRequest := _DeleteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteRequest)

	if err != nil {
		return err
	}

	*o = DeleteRequest(varDeleteRequest)

	return err
}

type NullableDeleteRequest struct {
	value *DeleteRequest
	isSet bool
}

func (v NullableDeleteRequest) Get() *DeleteRequest {
	return v.value
}

func (v *NullableDeleteRequest) Set(val *DeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteRequest(val *DeleteRequest) *NullableDeleteRequest {
	return &NullableDeleteRequest{value: val, isSet: true}
}

func (v NullableDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


