/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cyborgdb

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrainRequest{}

// TrainRequest struct for TrainRequest
type TrainRequest struct {
	BatchSize int32 `json:"batch_size"`
	MaxIterations int32 `json:"max_iterations"`
	Tolerance float64 `json:"tolerance"`
}

type _TrainRequest TrainRequest

// NewTrainRequest instantiates a new TrainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrainRequest(batchSize int32, maxIterations int32, tolerance float64) *TrainRequest {
	this := TrainRequest{}
	this.BatchSize = batchSize
	this.MaxIterations = maxIterations
	this.Tolerance = tolerance
	return &this
}

// NewTrainRequestWithDefaults instantiates a new TrainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrainRequestWithDefaults() *TrainRequest {
	this := TrainRequest{}
	return &this
}

// GetBatchSize returns the BatchSize field value
func (o *TrainRequest) GetBatchSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BatchSize
}

// GetBatchSizeOk returns a tuple with the BatchSize field value
// and a boolean to check if the value has been set.
func (o *TrainRequest) GetBatchSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BatchSize, true
}

// SetBatchSize sets field value
func (o *TrainRequest) SetBatchSize(v int32) {
	o.BatchSize = v
}

// GetMaxIterations returns the MaxIterations field value
func (o *TrainRequest) GetMaxIterations() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxIterations
}

// GetMaxIterationsOk returns a tuple with the MaxIterations field value
// and a boolean to check if the value has been set.
func (o *TrainRequest) GetMaxIterationsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxIterations, true
}

// SetMaxIterations sets field value
func (o *TrainRequest) SetMaxIterations(v int32) {
	o.MaxIterations = v
}

// GetTolerance returns the Tolerance field value
func (o *TrainRequest) GetTolerance() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Tolerance
}

// GetToleranceOk returns a tuple with the Tolerance field value
// and a boolean to check if the value has been set.
func (o *TrainRequest) GetToleranceOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tolerance, true
}

// SetTolerance sets field value
func (o *TrainRequest) SetTolerance(v float64) {
	o.Tolerance = v
}

func (o TrainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["batch_size"] = o.BatchSize
	toSerialize["max_iterations"] = o.MaxIterations
	toSerialize["tolerance"] = o.Tolerance
	return toSerialize, nil
}

func (o *TrainRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"batch_size",
		"max_iterations",
		"tolerance",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrainRequest := _TrainRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrainRequest)

	if err != nil {
		return err
	}

	*o = TrainRequest(varTrainRequest)

	return err
}

type NullableTrainRequest struct {
	value *TrainRequest
	isSet bool
}

func (v NullableTrainRequest) Get() *TrainRequest {
	return v.value
}

func (v *NullableTrainRequest) Set(val *TrainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTrainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTrainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrainRequest(val *TrainRequest) *NullableTrainRequest {
	return &NullableTrainRequest{value: val, isSet: true}
}

func (v NullableTrainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


