// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cyborgdb
// IndexListResponseModel represents the response returned from the ListIndexes API call.
// It contains a list of available encrypted index names.
type IndexListResponseModel struct {
	Indexes []string `json:"indexes"`
}
