/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cyborgdb

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpsertRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertRequest{}

// UpsertRequest struct for UpsertRequest
type UpsertRequest struct {
	IndexKey  string       `json:"index_key"`
	IndexName string       `json:"index_name"`
	Items     []VectorItem `json:"items"`
}

type _UpsertRequest UpsertRequest

// NewUpsertRequest instantiates a new UpsertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertRequest(indexKey string, indexName string, items []VectorItem) *UpsertRequest {
	this := UpsertRequest{}
	this.IndexKey = indexKey
	this.IndexName = indexName
	this.Items = items
	return &this
}

// NewUpsertRequestWithDefaults instantiates a new UpsertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertRequestWithDefaults() *UpsertRequest {
	this := UpsertRequest{}
	return &this
}

// GetItems returns the Items field value
func (o *UpsertRequest) GetItems() []VectorItem {
	if o == nil {
		var ret []VectorItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *UpsertRequest) GetItemsOk() ([]VectorItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *UpsertRequest) SetItems(v []VectorItem) {
	o.Items = v
}

func (o UpsertRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index_key"] = o.IndexKey   
	toSerialize["index_name"] = o.IndexName 
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *UpsertRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index_key", 
		"index_name", 
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpsertRequest := _UpsertRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpsertRequest)

	if err != nil {
		return err
	}

	*o = UpsertRequest(varUpsertRequest)

	return err
}

type NullableUpsertRequest struct {
	value *UpsertRequest
	isSet bool
}

func (v NullableUpsertRequest) Get() *UpsertRequest {
	return v.value
}

func (v *NullableUpsertRequest) Set(val *UpsertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertRequest(val *UpsertRequest) *NullableUpsertRequest {
	return &NullableUpsertRequest{value: val, isSet: true}
}

func (v NullableUpsertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
