/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cyborgdb

import (
	"encoding/json"
)

// checks if the EncryptedIndex type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EncryptedIndex{}

// EncryptedIndex struct for EncryptedIndex
type EncryptedIndex struct {
	IndexName *string `json:"index_name,omitempty"`
	IndexKey    string
	IndexType *string `json:"index_type,omitempty"`
	Config *IndexConfig `json:"config,omitempty"`
}

// NewEncryptedIndex instantiates a new EncryptedIndex object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEncryptedIndex() *EncryptedIndex {
	this := EncryptedIndex{}
	return &this
}

// NewEncryptedIndexWithDefaults instantiates a new EncryptedIndex object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEncryptedIndexWithDefaults() *EncryptedIndex {
	this := EncryptedIndex{}
	return &this
}

// GetIndexName returns the IndexName field value if set, zero value otherwise.
func (o *EncryptedIndex) GetIndexName() string {
	if o == nil || IsNil(o.IndexName) {
		var ret string
		return ret
	}
	return *o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncryptedIndex) GetIndexNameOk() (*string, bool) {
	if o == nil || IsNil(o.IndexName) {
		return nil, false
	}
	return o.IndexName, true
}

// HasIndexName returns a boolean if a field has been set.
func (o *EncryptedIndex) HasIndexName() bool {
	if o != nil && !IsNil(o.IndexName) {
		return true
	}

	return false
}

// SetIndexName gets a reference to the given string and assigns it to the IndexName field.
func (o *EncryptedIndex) SetIndexName(v string) {
	o.IndexName = &v
}

// GetIndexType returns the IndexType field value if set, zero value otherwise.
func (o *EncryptedIndex) GetIndexType() string {
	if o == nil || IsNil(o.IndexType) {
		var ret string
		return ret
	}
	return *o.IndexType
}

// GetIndexTypeOk returns a tuple with the IndexType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncryptedIndex) GetIndexTypeOk() (*string, bool) {
	if o == nil || IsNil(o.IndexType) {
		return nil, false
	}
	return o.IndexType, true
}

// HasIndexType returns a boolean if a field has been set.
func (o *EncryptedIndex) HasIndexType() bool {
	if o != nil && !IsNil(o.IndexType) {
		return true
	}

	return false
}

// SetIndexType gets a reference to the given string and assigns it to the IndexType field.
func (o *EncryptedIndex) SetIndexType(v string) {
	o.IndexType = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *EncryptedIndex) GetConfig() IndexConfig {
	if o == nil || IsNil(o.Config) {
		var ret IndexConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncryptedIndex) GetConfigOk() (*IndexConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *EncryptedIndex) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given IndexConfig and assigns it to the Config field.
func (o *EncryptedIndex) SetConfig(v IndexConfig) {
	o.Config = &v
}

func (o EncryptedIndex) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EncryptedIndex) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IndexName) {
		toSerialize["index_name"] = o.IndexName
	}
	if !IsNil(o.IndexType) {
		toSerialize["index_type"] = o.IndexType
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableEncryptedIndex struct {
	value *EncryptedIndex
	isSet bool
}

func (v NullableEncryptedIndex) Get() *EncryptedIndex {
	return v.value
}

func (v *NullableEncryptedIndex) Set(val *EncryptedIndex) {
	v.value = val
	v.isSet = true
}

func (v NullableEncryptedIndex) IsSet() bool {
	return v.isSet
}

func (v *NullableEncryptedIndex) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEncryptedIndex(val *EncryptedIndex) *NullableEncryptedIndex {
	return &NullableEncryptedIndex{value: val, isSet: true}
}

func (v NullableEncryptedIndex) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEncryptedIndex) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


