/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRequest{}

// GetRequest represents a request to retrieve specific vectors from an encrypted index by their IDs.
// This struct is used to specify which vectors to retrieve and what fields to include in the response.
// The request supports selective field inclusion to optimize bandwidth and response size.
type GetRequest struct {
	// IndexName specifies the name of the encrypted index from which to retrieve vectors.
	// This must match exactly with an existing index name in the CyborgDB instance.
	IndexName string `json:"index_name"`
	
	// IndexKey is the hexadecimal-encoded encryption key for the index.
	// This key is required to decrypt and access the vectors stored in the encrypted index.
	// The key must be a 64-character hexadecimal string representing 32 bytes of key data.
	IndexKey string `json:"index_key"`
	
	// Ids contains the list of unique identifiers for the vectors to retrieve.
	// Each ID should correspond to a vector that was previously upserted into the index.
	// If an ID doesn't exist in the index, it will be silently ignored (no error will be returned).
	Ids []string `json:"ids"`
	
	// Include specifies which fields to include in the response for each retrieved vector.
	// This field is optional and allows for selective field retrieval to optimize response size.
	// Available field options:
	//   - "vector": Include the high-dimensional vector embeddings
	//   - "metadata": Include associated metadata key-value pairs
	//   - "contents": Include text or binary content associated with the vector
	// If omitted, the server will include all available fields by default.
	Include []string `json:"include,omitempty"`
}

type _GetRequest GetRequest

// NewGetRequest instantiates a new GetRequest object with required parameters.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
//
// Parameters:
//   - indexName: The name of the encrypted index to retrieve vectors from
//   - indexKey: The hexadecimal-encoded encryption key for the index
//   - ids: Slice of string IDs identifying the vectors to retrieve
//
// Returns:
//   - *GetRequest: A pointer to the newly created GetRequest instance
//
// Example:
//   request := NewGetRequest("my-index", "a1b2c3d4...", []string{"vec1", "vec2"})
func NewGetRequest(indexName string, indexKey string, ids []string) *GetRequest {
	this := GetRequest{}
	this.IndexName = indexName
	this.IndexKey = indexKey
	this.Ids = ids
	return &this
}

// NewGetRequestWithDefaults instantiates a new GetRequest object with default values.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set.
//
// Returns:
//   - *GetRequest: A pointer to the newly created GetRequest instance
func NewGetRequestWithDefaults() *GetRequest {
	this := GetRequest{}
	return &this
}

// GetIndexName returns the IndexName field value.
// This method retrieves the name of the encrypted index from which vectors will be retrieved.
//
// Returns:
//   - string: The index name
func (o *GetRequest) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value and a boolean indicating if the value was set.
// This method is useful when you need to distinguish between an empty string and an unset value.
//
// Returns:
//   - *string: Pointer to the index name
//   - bool: true if the index name was set, false otherwise
func (o *GetRequest) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets the IndexName field value.
// This method assigns the name of the encrypted index from which to retrieve vectors.
//
// Parameters:
//   - v: The index name to set
func (o *GetRequest) SetIndexName(v string) {
	o.IndexName = v
}

// GetIndexKey returns the IndexKey field value.
// This method retrieves the hexadecimal-encoded encryption key for the index.
//
// Returns:
//   - string: The encryption key in hexadecimal format
func (o *GetRequest) GetIndexKey() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.IndexKey
}

// GetIndexKeyOk returns a tuple with the IndexKey field value and a boolean indicating if the value was set.
// This method is useful when you need to distinguish between an empty string and an unset value.
//
// Returns:
//   - *string: Pointer to the index key
//   - bool: true if the index key was set, false otherwise
func (o *GetRequest) GetIndexKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexKey, true
}

// SetIndexKey sets the IndexKey field value.
// This method assigns the hexadecimal-encoded encryption key for the index.
//
// Parameters:
//   - v: The encryption key in hexadecimal format (must be 64-character hex string)
func (o *GetRequest) SetIndexKey(v string) {
	o.IndexKey = v
}

// GetIds returns the Ids field value.
// This method retrieves the list of vector IDs to be retrieved from the index.
//
// Returns:
//   - []string: Slice of vector IDs
func (o *GetRequest) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value and a boolean indicating if the value was set.
// This method is useful when you need to distinguish between an empty slice and an unset value.
//
// Returns:
//   - []string: Slice of vector IDs
//   - bool: true if the IDs were set, false otherwise
func (o *GetRequest) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets the Ids field value.
// This method assigns the list of vector IDs to retrieve from the index.
//
// Parameters:
//   - v: Slice of string IDs identifying the vectors to retrieve
func (o *GetRequest) SetIds(v []string) {
	o.Ids = v
}

// GetInclude returns the Include field value if set, zero value otherwise.
// This method retrieves the list of fields to include in the response.
//
// Returns:
//   - []string: Slice of field names to include, or empty slice if not set
func (o *GetRequest) GetInclude() []string {
	if o == nil || IsNil(o.Include) {
		var ret []string
		return ret
	}
	return o.Include
}

// GetIncludeOk returns a tuple with the Include field value if set, nil otherwise
// and a boolean to check if the value has been set.
// This method is useful when you need to distinguish between an empty slice and an unset value.
//
// Returns:
//   - []string: Slice of field names to include
//   - bool: true if the include fields were set, false otherwise
func (o *GetRequest) GetIncludeOk() ([]string, bool) {
	if o == nil || IsNil(o.Include) {
		return nil, false
	}
	return o.Include, true
}

// HasInclude returns a boolean indicating whether the Include field has been set.
// This method checks if specific fields to include have been specified in the request.
//
// Returns:
//   - bool: true if include fields are specified, false otherwise
func (o *GetRequest) HasInclude() bool {
	if o != nil && !IsNil(o.Include) {
		return true
	}
	return false
}

// SetInclude gets a reference to the given []string and assigns it to the Include field.
// This method specifies which fields to include in the response for each retrieved vector.
//
// Parameters:
//   - v: Slice of field names to include ("vector", "metadata", "contents")
//
// Example:
//   request.SetInclude([]string{"vector", "metadata"})  // Include only vectors and metadata
//   request.SetInclude([]string{"metadata"})            // Include only metadata
//   request.SetInclude([]string{"vector", "metadata", "contents"}) // Include all fields
func (o *GetRequest) SetInclude(v []string) {
	o.Include = v
}

// MarshalJSON converts the GetRequest to JSON format.
// This method serializes the GetRequest struct into a JSON byte array suitable for API transmission.
//
// Returns:
//   - []byte: The JSON representation of the GetRequest
//   - error: Any error that occurred during marshaling
func (o GetRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

// ToMap converts the GetRequest to a map representation suitable for JSON serialization.
// This method creates a map containing all the fields of the GetRequest, handling optional fields appropriately.
//
// Returns:
//   - map[string]interface{}: A map containing the serializable fields
//   - error: Any error that occurred during conversion (currently always nil)
func (o GetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index_name"] = o.IndexName
	toSerialize["index_key"] = o.IndexKey
	toSerialize["ids"] = o.Ids
	if !IsNil(o.Include) {
		toSerialize["include"] = o.Include
	}
	return toSerialize, nil
}

// UnmarshalJSON deserializes JSON data into the GetRequest struct.
// This method validates that all required properties are included in the JSON object
// by unmarshalling the object into a generic map with string keys and checking
// that every required field exists as a key in the generic map.
//
// Parameters:
//   - data: The JSON data to unmarshal
//
// Returns:
//   - error: Any error that occurred during unmarshaling, including missing required fields
func (o *GetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	requiredProperties := []string{
		"index_name",
		"index_key", 
		"ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)
	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRequest := _GetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRequest)

	if err != nil {
		return err
	}

	*o = GetRequest(varGetRequest)

	return err
}

// NullableGetRequest is a wrapper that allows GetRequest to be nullable.
// It tracks whether the value has been explicitly set, which is useful for API serialization
// where you need to distinguish between a zero value and an explicitly set value.
type NullableGetRequest struct {
	value *GetRequest
	isSet bool
}

// Get retrieves the underlying GetRequest value.
//
// Returns:
//   - *GetRequest: The wrapped GetRequest value, or nil if not set
func (v NullableGetRequest) Get() *GetRequest {
	return v.value
}

// Set assigns a new GetRequest value and marks it as set.
//
// Parameters:
//   - val: The GetRequest value to set
func (v *NullableGetRequest) Set(val *GetRequest) {
	v.value = val
	v.isSet = true
}

// IsSet checks whether a value has been explicitly set.
//
// Returns:
//   - bool: true if a value has been set, false otherwise
func (v NullableGetRequest) IsSet() bool {
	return v.isSet
}

// Unset clears the value and marks it as not set.
func (v *NullableGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

// NewNullableGetRequest creates a new NullableGetRequest with the given value.
//
// Parameters:
//   - val: The GetRequest value to wrap
//
// Returns:
//   - *NullableGetRequest: A new NullableGetRequest instance
func NewNullableGetRequest(val *GetRequest) *NullableGetRequest {
	return &NullableGetRequest{value: val, isSet: true}
}

// MarshalJSON converts the NullableGetRequest to JSON format.
//
// Returns:
//   - []byte: The JSON representation of the wrapped value
//   - error: Any error that occurred during marshaling
func (v NullableGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

// UnmarshalJSON deserializes JSON data into the NullableGetRequest.
//
// Parameters:
//   - src: The JSON data to unmarshal
//
// Returns:
//   - error: Any error that occurred during unmarshaling
func (v *NullableGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}