/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.15.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
)

// checks if the IndexIVFSQModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexIVFSQModel{}

// IndexIVFSQModel Model for configuring an IVFSQ (Inverted File with Scalar Quantization) index.  Attributes:     type (str): Index type identifier. Defaults to \"ivfsq\".     sq_bits (int): Number of bits per dimension for scalar quantization. Defaults to 8.
type IndexIVFSQModel struct {
	Dimension NullableInt32 `json:"dimension,omitempty"`
	Type *string `json:"type,omitempty"`
	SqBits *int32 `json:"sq_bits,omitempty"`
}

// NewIndexIVFSQModel instantiates a new IndexIVFSQModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexIVFSQModel() *IndexIVFSQModel {
	this := IndexIVFSQModel{}
	var type_ string = "ivfsq"
	this.Type = &type_
	var sqBits int32 = 8
	this.SqBits = &sqBits
	return &this
}

// NewIndexIVFSQModelWithDefaults instantiates a new IndexIVFSQModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexIVFSQModelWithDefaults() *IndexIVFSQModel {
	this := IndexIVFSQModel{}
	var type_ string = "ivfsq"
	this.Type = &type_
	var sqBits int32 = 8
	this.SqBits = &sqBits
	return &this
}

// GetDimension returns the Dimension field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexIVFSQModel) GetDimension() int32 {
	if o == nil || IsNil(o.Dimension.Get()) {
		var ret int32
		return ret
	}
	return *o.Dimension.Get()
}

// GetDimensionOk returns a tuple with the Dimension field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexIVFSQModel) GetDimensionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dimension.Get(), o.Dimension.IsSet()
}

// HasDimension returns a boolean if a field has been set.
func (o *IndexIVFSQModel) HasDimension() bool {
	if o != nil && o.Dimension.IsSet() {
		return true
	}

	return false
}

// SetDimension gets a reference to the given NullableInt32 and assigns it to the Dimension field.
func (o *IndexIVFSQModel) SetDimension(v int32) {
	o.Dimension.Set(&v)
}
// SetDimensionNil sets the value for Dimension to be an explicit nil
func (o *IndexIVFSQModel) SetDimensionNil() {
	o.Dimension.Set(nil)
}

// UnsetDimension ensures that no value is present for Dimension, not even an explicit nil
func (o *IndexIVFSQModel) UnsetDimension() {
	o.Dimension.Unset()
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IndexIVFSQModel) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexIVFSQModel) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IndexIVFSQModel) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IndexIVFSQModel) SetType(v string) {
	o.Type = &v
}

// GetSqBits returns the SqBits field value if set, zero value otherwise.
func (o *IndexIVFSQModel) GetSqBits() int32 {
	if o == nil || IsNil(o.SqBits) {
		var ret int32
		return ret
	}
	return *o.SqBits
}

// GetSqBitsOk returns a tuple with the SqBits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexIVFSQModel) GetSqBitsOk() (*int32, bool) {
	if o == nil || IsNil(o.SqBits) {
		return nil, false
	}
	return o.SqBits, true
}

// HasSqBits returns a boolean if a field has been set.
func (o *IndexIVFSQModel) HasSqBits() bool {
	if o != nil && !IsNil(o.SqBits) {
		return true
	}

	return false
}

// SetSqBits gets a reference to the given int32 and assigns it to the SqBits field.
func (o *IndexIVFSQModel) SetSqBits(v int32) {
	o.SqBits = &v
}

func (o IndexIVFSQModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexIVFSQModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Dimension.IsSet() {
		toSerialize["dimension"] = o.Dimension.Get()
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.SqBits) {
		toSerialize["sq_bits"] = o.SqBits
	}
	return toSerialize, nil
}

type NullableIndexIVFSQModel struct {
	value *IndexIVFSQModel
	isSet bool
}

func (v NullableIndexIVFSQModel) Get() *IndexIVFSQModel {
	return v.value
}

func (v *NullableIndexIVFSQModel) Set(val *IndexIVFSQModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexIVFSQModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexIVFSQModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexIVFSQModel(val *IndexIVFSQModel) *NullableIndexIVFSQModel {
	return &NullableIndexIVFSQModel{value: val, isSet: true}
}

func (v NullableIndexIVFSQModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexIVFSQModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


