/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.17.1.dev16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IndexInfoResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexInfoResponseModel{}

// IndexInfoResponseModel Response model for retrieving information about an index.  Attributes:     index_name (str): The name of the index.     is_trained (bool): Indicates whether the index has been trained.     dimension (int): Dimensionality of the vectors. `0` before the         first upsert when create_index was called without an explicit         dimension (auto-detect).     metric (str): Distance metric (`euclidean`, `cosine`, or         `squared_euclidean`).     n_lists (int): Number of inverted lists in the IVF index. `1`         for untrained indexes.     metadata_schema (Dict[str, MetadataFieldPolicy]): Per-field metadata         indexing overrides recorded at create time. Empty when the         index uses the default index-everything posture.
type IndexInfoResponseModel struct {
	IndexName string `json:"index_name"`
	IsTrained bool `json:"is_trained"`
	Dimension int32 `json:"dimension"`
	Metric string `json:"metric"`
	NLists int32 `json:"n_lists"`
	MetadataSchema map[string]MetadataFieldPolicy `json:"metadata_schema,omitempty"`
}

type _IndexInfoResponseModel IndexInfoResponseModel

// NewIndexInfoResponseModel instantiates a new IndexInfoResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexInfoResponseModel(indexName string, isTrained bool, dimension int32, metric string, nLists int32) *IndexInfoResponseModel {
	this := IndexInfoResponseModel{}
	this.IndexName = indexName
	this.IsTrained = isTrained
	this.Dimension = dimension
	this.Metric = metric
	this.NLists = nLists
	return &this
}

// NewIndexInfoResponseModelWithDefaults instantiates a new IndexInfoResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexInfoResponseModelWithDefaults() *IndexInfoResponseModel {
	this := IndexInfoResponseModel{}
	return &this
}

// GetIndexName returns the IndexName field value
func (o *IndexInfoResponseModel) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *IndexInfoResponseModel) SetIndexName(v string) {
	o.IndexName = v
}

// GetIsTrained returns the IsTrained field value
func (o *IndexInfoResponseModel) GetIsTrained() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsTrained
}

// GetIsTrainedOk returns a tuple with the IsTrained field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetIsTrainedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsTrained, true
}

// SetIsTrained sets field value
func (o *IndexInfoResponseModel) SetIsTrained(v bool) {
	o.IsTrained = v
}

// GetDimension returns the Dimension field value
func (o *IndexInfoResponseModel) GetDimension() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Dimension
}

// GetDimensionOk returns a tuple with the Dimension field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetDimensionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dimension, true
}

// SetDimension sets field value
func (o *IndexInfoResponseModel) SetDimension(v int32) {
	o.Dimension = v
}

// GetMetric returns the Metric field value
func (o *IndexInfoResponseModel) GetMetric() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetMetricOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *IndexInfoResponseModel) SetMetric(v string) {
	o.Metric = v
}

// GetNLists returns the NLists field value
func (o *IndexInfoResponseModel) GetNLists() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NLists
}

// GetNListsOk returns a tuple with the NLists field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetNListsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NLists, true
}

// SetNLists sets field value
func (o *IndexInfoResponseModel) SetNLists(v int32) {
	o.NLists = v
}

// GetMetadataSchema returns the MetadataSchema field value if set, zero value otherwise.
func (o *IndexInfoResponseModel) GetMetadataSchema() map[string]MetadataFieldPolicy {
	if o == nil || IsNil(o.MetadataSchema) {
		var ret map[string]MetadataFieldPolicy
		return ret
	}
	return o.MetadataSchema
}

// GetMetadataSchemaOk returns a tuple with the MetadataSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetMetadataSchemaOk() (map[string]MetadataFieldPolicy, bool) {
	if o == nil || IsNil(o.MetadataSchema) {
		return map[string]MetadataFieldPolicy{}, false
	}
	return o.MetadataSchema, true
}

// HasMetadataSchema returns a boolean if a field has been set.
func (o *IndexInfoResponseModel) HasMetadataSchema() bool {
	if o != nil && !IsNil(o.MetadataSchema) {
		return true
	}

	return false
}

// SetMetadataSchema gets a reference to the given map[string]MetadataFieldPolicy and assigns it to the MetadataSchema field.
func (o *IndexInfoResponseModel) SetMetadataSchema(v map[string]MetadataFieldPolicy) {
	o.MetadataSchema = v
}

func (o IndexInfoResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexInfoResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index_name"] = o.IndexName
	toSerialize["is_trained"] = o.IsTrained
	toSerialize["dimension"] = o.Dimension
	toSerialize["metric"] = o.Metric
	toSerialize["n_lists"] = o.NLists
	if !IsNil(o.MetadataSchema) {
		toSerialize["metadata_schema"] = o.MetadataSchema
	}
	return toSerialize, nil
}

func (o *IndexInfoResponseModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index_name",
		"is_trained",
		"dimension",
		"metric",
		"n_lists",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIndexInfoResponseModel := _IndexInfoResponseModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	
	err = decoder.Decode(&varIndexInfoResponseModel)

	if err != nil {
		return err
	}

	*o = IndexInfoResponseModel(varIndexInfoResponseModel)

	return err
}

type NullableIndexInfoResponseModel struct {
	value *IndexInfoResponseModel
	isSet bool
}

func (v NullableIndexInfoResponseModel) Get() *IndexInfoResponseModel {
	return v.value
}

func (v *NullableIndexInfoResponseModel) Set(val *IndexInfoResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexInfoResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexInfoResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexInfoResponseModel(val *IndexInfoResponseModel) *NullableIndexInfoResponseModel {
	return &NullableIndexInfoResponseModel{value: val, isSet: true}
}

func (v NullableIndexInfoResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexInfoResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


