/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.17.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BinaryQueryBatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BinaryQueryBatch{}

// BinaryQueryBatch Represents a batch of query vectors in binary format for efficient transfer.  Attributes:     vectors_b64 (str): Base64-encoded float32 numpy array (shape: n_queries x dimension).     dimension (int): The dimension of each vector.
type BinaryQueryBatch struct {
	Dimension int32 `json:"dimension"`
	VectorsB64 string `json:"vectors_b64"`
}

type _BinaryQueryBatch BinaryQueryBatch

// NewBinaryQueryBatch instantiates a new BinaryQueryBatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBinaryQueryBatch(dimension int32, vectorsB64 string) *BinaryQueryBatch {
	this := BinaryQueryBatch{}
	this.Dimension = dimension
	this.VectorsB64 = vectorsB64
	return &this
}

// NewBinaryQueryBatchWithDefaults instantiates a new BinaryQueryBatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBinaryQueryBatchWithDefaults() *BinaryQueryBatch {
	this := BinaryQueryBatch{}
	return &this
}

// GetDimension returns the Dimension field value
func (o *BinaryQueryBatch) GetDimension() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Dimension
}

// GetDimensionOk returns a tuple with the Dimension field value
// and a boolean to check if the value has been set.
func (o *BinaryQueryBatch) GetDimensionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dimension, true
}

// SetDimension sets field value
func (o *BinaryQueryBatch) SetDimension(v int32) {
	o.Dimension = v
}

// GetVectorsB64 returns the VectorsB64 field value
func (o *BinaryQueryBatch) GetVectorsB64() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VectorsB64
}

// GetVectorsB64Ok returns a tuple with the VectorsB64 field value
// and a boolean to check if the value has been set.
func (o *BinaryQueryBatch) GetVectorsB64Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VectorsB64, true
}

// SetVectorsB64 sets field value
func (o *BinaryQueryBatch) SetVectorsB64(v string) {
	o.VectorsB64 = v
}

func (o BinaryQueryBatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BinaryQueryBatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dimension"] = o.Dimension
	toSerialize["vectors_b64"] = o.VectorsB64
	return toSerialize, nil
}

func (o *BinaryQueryBatch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dimension",
		"vectors_b64",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBinaryQueryBatch := _BinaryQueryBatch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	
	err = decoder.Decode(&varBinaryQueryBatch)

	if err != nil {
		return err
	}

	*o = BinaryQueryBatch(varBinaryQueryBatch)

	return err
}

type NullableBinaryQueryBatch struct {
	value *BinaryQueryBatch
	isSet bool
}

func (v NullableBinaryQueryBatch) Get() *BinaryQueryBatch {
	return v.value
}

func (v *NullableBinaryQueryBatch) Set(val *BinaryQueryBatch) {
	v.value = val
	v.isSet = true
}

func (v NullableBinaryQueryBatch) IsSet() bool {
	return v.isSet
}

func (v *NullableBinaryQueryBatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBinaryQueryBatch(val *BinaryQueryBatch) *NullableBinaryQueryBatch {
	return &NullableBinaryQueryBatch{value: val, isSet: true}
}

func (v NullableBinaryQueryBatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBinaryQueryBatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


