/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.16.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IndexTrainingStatusResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexTrainingStatusResponseModel{}

// IndexTrainingStatusResponseModel Response model for retrieving the training status of indexes.  Attributes:     training_indexes (List[str]): List of index names currently being trained or queued.     retrain_threshold (int): The multiplier used for the retraining threshold.     currently_training (Optional[str]): Name of the index currently being trained.     queued_indexes (List[str]): List of indexes queued for training.     worker_running (bool): Whether the training worker thread is running.     worker_pid (int): Deprecated - kept for backward compatibility with SDK.     global_training (Dict[str, Any]): Deprecated - kept for backward compatibility with SDK.
type IndexTrainingStatusResponseModel struct {
	TrainingIndexes []string `json:"training_indexes"`
	RetrainThreshold int32 `json:"retrain_threshold"`
	CurrentlyTraining NullableString `json:"currently_training,omitempty"`
	QueuedIndexes []string `json:"queued_indexes,omitempty"`
	WorkerRunning *bool `json:"worker_running,omitempty"`
	WorkerPid *int32 `json:"worker_pid,omitempty"`
	GlobalTraining map[string]interface{} `json:"global_training,omitempty"`
}

type _IndexTrainingStatusResponseModel IndexTrainingStatusResponseModel

// NewIndexTrainingStatusResponseModel instantiates a new IndexTrainingStatusResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexTrainingStatusResponseModel(trainingIndexes []string, retrainThreshold int32) *IndexTrainingStatusResponseModel {
	this := IndexTrainingStatusResponseModel{}
	this.TrainingIndexes = trainingIndexes
	this.RetrainThreshold = retrainThreshold
	var workerRunning bool = false
	this.WorkerRunning = &workerRunning
	var workerPid int32 = 0
	this.WorkerPid = &workerPid
	return &this
}

// NewIndexTrainingStatusResponseModelWithDefaults instantiates a new IndexTrainingStatusResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexTrainingStatusResponseModelWithDefaults() *IndexTrainingStatusResponseModel {
	this := IndexTrainingStatusResponseModel{}
	var workerRunning bool = false
	this.WorkerRunning = &workerRunning
	var workerPid int32 = 0
	this.WorkerPid = &workerPid
	return &this
}

// GetTrainingIndexes returns the TrainingIndexes field value
func (o *IndexTrainingStatusResponseModel) GetTrainingIndexes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TrainingIndexes
}

// GetTrainingIndexesOk returns a tuple with the TrainingIndexes field value
// and a boolean to check if the value has been set.
func (o *IndexTrainingStatusResponseModel) GetTrainingIndexesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrainingIndexes, true
}

// SetTrainingIndexes sets field value
func (o *IndexTrainingStatusResponseModel) SetTrainingIndexes(v []string) {
	o.TrainingIndexes = v
}

// GetRetrainThreshold returns the RetrainThreshold field value
func (o *IndexTrainingStatusResponseModel) GetRetrainThreshold() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RetrainThreshold
}

// GetRetrainThresholdOk returns a tuple with the RetrainThreshold field value
// and a boolean to check if the value has been set.
func (o *IndexTrainingStatusResponseModel) GetRetrainThresholdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetrainThreshold, true
}

// SetRetrainThreshold sets field value
func (o *IndexTrainingStatusResponseModel) SetRetrainThreshold(v int32) {
	o.RetrainThreshold = v
}

// GetCurrentlyTraining returns the CurrentlyTraining field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexTrainingStatusResponseModel) GetCurrentlyTraining() string {
	if o == nil || IsNil(o.CurrentlyTraining.Get()) {
		var ret string
		return ret
	}
	return *o.CurrentlyTraining.Get()
}

// GetCurrentlyTrainingOk returns a tuple with the CurrentlyTraining field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexTrainingStatusResponseModel) GetCurrentlyTrainingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentlyTraining.Get(), o.CurrentlyTraining.IsSet()
}

// HasCurrentlyTraining returns a boolean if a field has been set.
func (o *IndexTrainingStatusResponseModel) HasCurrentlyTraining() bool {
	if o != nil && o.CurrentlyTraining.IsSet() {
		return true
	}

	return false
}

// SetCurrentlyTraining gets a reference to the given NullableString and assigns it to the CurrentlyTraining field.
func (o *IndexTrainingStatusResponseModel) SetCurrentlyTraining(v string) {
	o.CurrentlyTraining.Set(&v)
}
// SetCurrentlyTrainingNil sets the value for CurrentlyTraining to be an explicit nil
func (o *IndexTrainingStatusResponseModel) SetCurrentlyTrainingNil() {
	o.CurrentlyTraining.Set(nil)
}

// UnsetCurrentlyTraining ensures that no value is present for CurrentlyTraining, not even an explicit nil
func (o *IndexTrainingStatusResponseModel) UnsetCurrentlyTraining() {
	o.CurrentlyTraining.Unset()
}

// GetQueuedIndexes returns the QueuedIndexes field value if set, zero value otherwise.
func (o *IndexTrainingStatusResponseModel) GetQueuedIndexes() []string {
	if o == nil || IsNil(o.QueuedIndexes) {
		var ret []string
		return ret
	}
	return o.QueuedIndexes
}

// GetQueuedIndexesOk returns a tuple with the QueuedIndexes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexTrainingStatusResponseModel) GetQueuedIndexesOk() ([]string, bool) {
	if o == nil || IsNil(o.QueuedIndexes) {
		return nil, false
	}
	return o.QueuedIndexes, true
}

// HasQueuedIndexes returns a boolean if a field has been set.
func (o *IndexTrainingStatusResponseModel) HasQueuedIndexes() bool {
	if o != nil && !IsNil(o.QueuedIndexes) {
		return true
	}

	return false
}

// SetQueuedIndexes gets a reference to the given []string and assigns it to the QueuedIndexes field.
func (o *IndexTrainingStatusResponseModel) SetQueuedIndexes(v []string) {
	o.QueuedIndexes = v
}

// GetWorkerRunning returns the WorkerRunning field value if set, zero value otherwise.
func (o *IndexTrainingStatusResponseModel) GetWorkerRunning() bool {
	if o == nil || IsNil(o.WorkerRunning) {
		var ret bool
		return ret
	}
	return *o.WorkerRunning
}

// GetWorkerRunningOk returns a tuple with the WorkerRunning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexTrainingStatusResponseModel) GetWorkerRunningOk() (*bool, bool) {
	if o == nil || IsNil(o.WorkerRunning) {
		return nil, false
	}
	return o.WorkerRunning, true
}

// HasWorkerRunning returns a boolean if a field has been set.
func (o *IndexTrainingStatusResponseModel) HasWorkerRunning() bool {
	if o != nil && !IsNil(o.WorkerRunning) {
		return true
	}

	return false
}

// SetWorkerRunning gets a reference to the given bool and assigns it to the WorkerRunning field.
func (o *IndexTrainingStatusResponseModel) SetWorkerRunning(v bool) {
	o.WorkerRunning = &v
}

// GetWorkerPid returns the WorkerPid field value if set, zero value otherwise.
func (o *IndexTrainingStatusResponseModel) GetWorkerPid() int32 {
	if o == nil || IsNil(o.WorkerPid) {
		var ret int32
		return ret
	}
	return *o.WorkerPid
}

// GetWorkerPidOk returns a tuple with the WorkerPid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexTrainingStatusResponseModel) GetWorkerPidOk() (*int32, bool) {
	if o == nil || IsNil(o.WorkerPid) {
		return nil, false
	}
	return o.WorkerPid, true
}

// HasWorkerPid returns a boolean if a field has been set.
func (o *IndexTrainingStatusResponseModel) HasWorkerPid() bool {
	if o != nil && !IsNil(o.WorkerPid) {
		return true
	}

	return false
}

// SetWorkerPid gets a reference to the given int32 and assigns it to the WorkerPid field.
func (o *IndexTrainingStatusResponseModel) SetWorkerPid(v int32) {
	o.WorkerPid = &v
}

// GetGlobalTraining returns the GlobalTraining field value if set, zero value otherwise.
func (o *IndexTrainingStatusResponseModel) GetGlobalTraining() map[string]interface{} {
	if o == nil || IsNil(o.GlobalTraining) {
		var ret map[string]interface{}
		return ret
	}
	return o.GlobalTraining
}

// GetGlobalTrainingOk returns a tuple with the GlobalTraining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexTrainingStatusResponseModel) GetGlobalTrainingOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.GlobalTraining) {
		return map[string]interface{}{}, false
	}
	return o.GlobalTraining, true
}

// HasGlobalTraining returns a boolean if a field has been set.
func (o *IndexTrainingStatusResponseModel) HasGlobalTraining() bool {
	if o != nil && !IsNil(o.GlobalTraining) {
		return true
	}

	return false
}

// SetGlobalTraining gets a reference to the given map[string]interface{} and assigns it to the GlobalTraining field.
func (o *IndexTrainingStatusResponseModel) SetGlobalTraining(v map[string]interface{}) {
	o.GlobalTraining = v
}

func (o IndexTrainingStatusResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexTrainingStatusResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["training_indexes"] = o.TrainingIndexes
	toSerialize["retrain_threshold"] = o.RetrainThreshold
	if o.CurrentlyTraining.IsSet() {
		toSerialize["currently_training"] = o.CurrentlyTraining.Get()
	}
	if !IsNil(o.QueuedIndexes) {
		toSerialize["queued_indexes"] = o.QueuedIndexes
	}
	if !IsNil(o.WorkerRunning) {
		toSerialize["worker_running"] = o.WorkerRunning
	}
	if !IsNil(o.WorkerPid) {
		toSerialize["worker_pid"] = o.WorkerPid
	}
	if !IsNil(o.GlobalTraining) {
		toSerialize["global_training"] = o.GlobalTraining
	}
	return toSerialize, nil
}

func (o *IndexTrainingStatusResponseModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"training_indexes",
		"retrain_threshold",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIndexTrainingStatusResponseModel := _IndexTrainingStatusResponseModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	
	err = decoder.Decode(&varIndexTrainingStatusResponseModel)

	if err != nil {
		return err
	}

	*o = IndexTrainingStatusResponseModel(varIndexTrainingStatusResponseModel)

	return err
}

type NullableIndexTrainingStatusResponseModel struct {
	value *IndexTrainingStatusResponseModel
	isSet bool
}

func (v NullableIndexTrainingStatusResponseModel) Get() *IndexTrainingStatusResponseModel {
	return v.value
}

func (v *NullableIndexTrainingStatusResponseModel) Set(val *IndexTrainingStatusResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexTrainingStatusResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexTrainingStatusResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexTrainingStatusResponseModel(val *IndexTrainingStatusResponseModel) *NullableIndexTrainingStatusResponseModel {
	return &NullableIndexTrainingStatusResponseModel{value: val, isSet: true}
}

func (v NullableIndexTrainingStatusResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexTrainingStatusResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


