/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IndexConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexConfig{}

// IndexConfig struct for IndexConfig
type IndexConfig struct {
	Dimension int32 `json:"dimension"`
	Metric string `json:"metric"`
	IndexType string `json:"index_type"`
	NLists int32 `json:"n_lists"`
	PqDim *int32 `json:"pq_dim,omitempty"`
	PqBits *int32 `json:"pq_bits,omitempty"`
}

type _IndexConfig IndexConfig

// NewIndexConfig instantiates a new IndexConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexConfig(dimension int32, metric string, indexType string, nLists int32) *IndexConfig {
	this := IndexConfig{}
	this.Dimension = dimension
	this.Metric = metric
	this.IndexType = indexType
	this.NLists = nLists
	return &this
}

// NewIndexConfigWithDefaults instantiates a new IndexConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexConfigWithDefaults() *IndexConfig {
	this := IndexConfig{}
	return &this
}

// GetDimension returns the Dimension field value
func (o *IndexConfig) GetDimension() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Dimension
}

// GetDimensionOk returns a tuple with the Dimension field value
// and a boolean to check if the value has been set.
func (o *IndexConfig) GetDimensionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dimension, true
}

// SetDimension sets field value
func (o *IndexConfig) SetDimension(v int32) {
	o.Dimension = v
}

// GetMetric returns the Metric field value
func (o *IndexConfig) GetMetric() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *IndexConfig) GetMetricOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *IndexConfig) SetMetric(v string) {
	o.Metric = v
}

// GetIndexType returns the IndexType field value
func (o *IndexConfig) GetIndexType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexType
}

// GetIndexTypeOk returns a tuple with the IndexType field value
// and a boolean to check if the value has been set.
func (o *IndexConfig) GetIndexTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexType, true
}

// SetIndexType sets field value
func (o *IndexConfig) SetIndexType(v string) {
	o.IndexType = v
}

// GetNLists returns the NLists field value
func (o *IndexConfig) GetNLists() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NLists
}

// GetNListsOk returns a tuple with the NLists field value
// and a boolean to check if the value has been set.
func (o *IndexConfig) GetNListsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NLists, true
}

// SetNLists sets field value
func (o *IndexConfig) SetNLists(v int32) {
	o.NLists = v
}

// GetPqDim returns the PqDim field value if set, zero value otherwise.
func (o *IndexConfig) GetPqDim() int32 {
	if o == nil || IsNil(o.PqDim) {
		var ret int32
		return ret
	}
	return *o.PqDim
}

// GetPqDimOk returns a tuple with the PqDim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexConfig) GetPqDimOk() (*int32, bool) {
	if o == nil || IsNil(o.PqDim) {
		return nil, false
	}
	return o.PqDim, true
}

// HasPqDim returns a boolean if a field has been set.
func (o *IndexConfig) HasPqDim() bool {
	if o != nil && !IsNil(o.PqDim) {
		return true
	}

	return false
}

// SetPqDim gets a reference to the given int32 and assigns it to the PqDim field.
func (o *IndexConfig) SetPqDim(v int32) {
	o.PqDim = &v
}

// GetPqBits returns the PqBits field value if set, zero value otherwise.
func (o *IndexConfig) GetPqBits() int32 {
	if o == nil || IsNil(o.PqBits) {
		var ret int32
		return ret
	}
	return *o.PqBits
}

// GetPqBitsOk returns a tuple with the PqBits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexConfig) GetPqBitsOk() (*int32, bool) {
	if o == nil || IsNil(o.PqBits) {
		return nil, false
	}
	return o.PqBits, true
}

// HasPqBits returns a boolean if a field has been set.
func (o *IndexConfig) HasPqBits() bool {
	if o != nil && !IsNil(o.PqBits) {
		return true
	}

	return false
}

// SetPqBits gets a reference to the given int32 and assigns it to the PqBits field.
func (o *IndexConfig) SetPqBits(v int32) {
	o.PqBits = &v
}

func (o IndexConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dimension"] = o.Dimension
	toSerialize["metric"] = o.Metric
	toSerialize["index_type"] = o.IndexType
	toSerialize["n_lists"] = o.NLists
	if !IsNil(o.PqDim) {
		toSerialize["pq_dim"] = o.PqDim
	}
	if !IsNil(o.PqBits) {
		toSerialize["pq_bits"] = o.PqBits
	}
	return toSerialize, nil
}

func (o *IndexConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dimension",
		"metric",
		"index_type",
		"n_lists",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIndexConfig := _IndexConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIndexConfig)

	if err != nil {
		return err
	}

	*o = IndexConfig(varIndexConfig)

	return err
}

type NullableIndexConfig struct {
	value *IndexConfig
	isSet bool
}

func (v NullableIndexConfig) Get() *IndexConfig {
	return v.value
}

func (v *NullableIndexConfig) Set(val *IndexConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexConfig(val *IndexConfig) *NullableIndexConfig {
	return &NullableIndexConfig{value: val, isSet: true}
}

func (v NullableIndexConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


