/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryRequest{}

// QueryRequest struct for QueryRequest
type QueryRequest struct {
	IndexName     string                 `json:"index_name"`
	IndexKey      string                 `json:"index_key"`
	QueryVector   []float32              `json:"query_vector,omitempty"`
	QueryVectors  [][]float32            `json:"query_vectors,omitempty"`
	QueryContents *string                `json:"query_contents,omitempty"`
	TopK          int32                  `json:"top_k"`
	NProbes       int32                  `json:"n_probes"`
	Greedy        *bool                  `json:"greedy,omitempty"`
	Filters       map[string]interface{} `json:"filters,omitempty"`
	Include       []string               `json:"include"`
}

type _QueryRequest QueryRequest

// NewQueryRequest instantiates a new QueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryRequest(indexName string, indexKey string, topK int32, nProbes int32, include []string) *QueryRequest {
	this := QueryRequest{}
	this.IndexName = indexName
	this.IndexKey = indexKey
	this.TopK = topK
	this.NProbes = nProbes
	this.Include = include
	return &this
}

// NewQueryRequestWithDefaults instantiates a new QueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryRequestWithDefaults() *QueryRequest {
	this := QueryRequest{}
	return &this
}

// GetIndexName returns the IndexName field value
func (o *QueryRequest) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *QueryRequest) SetIndexName(v string) {
	o.IndexName = v
}

// GetIndexKey returns the IndexKey field value
func (o *QueryRequest) GetIndexKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexKey
}

// GetIndexKeyOk returns a tuple with the IndexKey field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetIndexKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexKey, true
}

// SetIndexKey sets field value
func (o *QueryRequest) SetIndexKey(v string) {
	o.IndexKey = v
}

// GetQueryVector returns the QueryVector field value if set, zero value otherwise.
func (o *QueryRequest) GetQueryVector() []float32 {
	if o == nil || IsNil(o.QueryVector) {
		var ret []float32
		return ret
	}
	return o.QueryVector
}

// GetQueryVectorOk returns a tuple with the QueryVector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetQueryVectorOk() ([]float32, bool) {
	if o == nil || IsNil(o.QueryVector) {
		return nil, false
	}
	return o.QueryVector, true
}

// HasQueryVector returns a boolean if a field has been set.
func (o *QueryRequest) HasQueryVector() bool {
	if o != nil && !IsNil(o.QueryVector) {
		return true
	}

	return false
}

// SetQueryVector gets a reference to the given []float32 and assigns it to the QueryVector field.
func (o *QueryRequest) SetQueryVector(v []float32) {
	o.QueryVector = v
}

// GetQueryVectors returns the QueryVectors field value if set, zero value otherwise.
func (o *QueryRequest) GetQueryVectors() [][]float32 {
	if o == nil || IsNil(o.QueryVectors) {
		var ret [][]float32
		return ret
	}
	return o.QueryVectors
}

// GetQueryVectorsOk returns a tuple with the QueryVectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetQueryVectorsOk() ([][]float32, bool) {
	if o == nil || IsNil(o.QueryVectors) {
		return nil, false
	}
	return o.QueryVectors, true
}

// HasQueryVectors returns a boolean if a field has been set.
func (o *QueryRequest) HasQueryVectors() bool {
	if o != nil && !IsNil(o.QueryVectors) {
		return true
	}

	return false
}

// SetQueryVectors gets a reference to the given [][]float32 and assigns it to the QueryVectors field.
func (o *QueryRequest) SetQueryVectors(v [][]float32) {
	o.QueryVectors = v
}

// GetQueryContents returns the QueryContents field value if set, zero value otherwise.
func (o *QueryRequest) GetQueryContents() string {
	if o == nil || IsNil(o.QueryContents) {
		var ret string
		return ret
	}
	return *o.QueryContents
}

// GetQueryContentsOk returns a tuple with the QueryContents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetQueryContentsOk() (*string, bool) {
	if o == nil || IsNil(o.QueryContents) {
		return nil, false
	}
	return o.QueryContents, true
}

// HasQueryContents returns a boolean if a field has been set.
func (o *QueryRequest) HasQueryContents() bool {
	if o != nil && !IsNil(o.QueryContents) {
		return true
	}

	return false
}

// SetQueryContents gets a reference to the given string and assigns it to the QueryContents field.
func (o *QueryRequest) SetQueryContents(v string) {
	o.QueryContents = &v
}

// GetTopK returns the TopK field value
func (o *QueryRequest) GetTopK() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TopK
}

// GetTopKOk returns a tuple with the TopK field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetTopKOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopK, true
}

// SetTopK sets field value
func (o *QueryRequest) SetTopK(v int32) {
	o.TopK = v
}

// GetNProbes returns the NProbes field value
func (o *QueryRequest) GetNProbes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NProbes
}

// GetNProbesOk returns a tuple with the NProbes field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetNProbesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NProbes, true
}

// SetNProbes sets field value
func (o *QueryRequest) SetNProbes(v int32) {
	o.NProbes = v
}

// GetGreedy returns the Greedy field value if set, zero value otherwise.
func (o *QueryRequest) GetGreedy() bool {
	if o == nil || IsNil(o.Greedy) {
		var ret bool
		return ret
	}
	return *o.Greedy
}

// GetGreedyOk returns a tuple with the Greedy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetGreedyOk() (*bool, bool) {
	if o == nil || IsNil(o.Greedy) {
		return nil, false
	}
	return o.Greedy, true
}

// HasGreedy returns a boolean if a field has been set.
func (o *QueryRequest) HasGreedy() bool {
	if o != nil && !IsNil(o.Greedy) {
		return true
	}

	return false
}

// SetGreedy gets a reference to the given bool and assigns it to the Greedy field.
func (o *QueryRequest) SetGreedy(v bool) {
	o.Greedy = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *QueryRequest) GetFilters() map[string]interface{} {
	if o == nil || IsNil(o.Filters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetFiltersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filters) {
		return map[string]interface{}{}, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *QueryRequest) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given map[string]interface{} and assigns it to the Filters field.
func (o *QueryRequest) SetFilters(v map[string]interface{}) {
	o.Filters = v
}

// GetInclude returns the Include field value
func (o *QueryRequest) GetInclude() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Include
}

// GetIncludeOk returns a tuple with the Include field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetIncludeOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Include, true
}

// SetInclude sets field value
func (o *QueryRequest) SetInclude(v []string) {
	o.Include = v
}

func (o QueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index_name"] = o.IndexName
	toSerialize["index_key"] = o.IndexKey
	if !IsNil(o.QueryVector) {
		toSerialize["query_vector"] = o.QueryVector
	}
	if !IsNil(o.QueryVectors) {
		toSerialize["query_vectors"] = o.QueryVectors
	}
	if !IsNil(o.QueryContents) {
		toSerialize["query_contents"] = o.QueryContents
	}
	toSerialize["top_k"] = o.TopK
	toSerialize["n_probes"] = o.NProbes
	if !IsNil(o.Greedy) {
		toSerialize["greedy"] = o.Greedy
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["include"] = o.Include
	return toSerialize, nil
}

func (o *QueryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index_name",
		"index_key",
		"top_k",
		"n_probes",
		"include",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryRequest := _QueryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryRequest)

	if err != nil {
		return err
	}

	*o = QueryRequest(varQueryRequest)

	return err
}

type NullableQueryRequest struct {
	value *QueryRequest
	isSet bool
}

func (v NullableQueryRequest) Get() *QueryRequest {
	return v.value
}

func (v *NullableQueryRequest) Set(val *QueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryRequest(val *QueryRequest) *NullableQueryRequest {
	return &NullableQueryRequest{value: val, isSet: true}
}

func (v NullableQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}