/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"fmt"
)


// IndexConfig struct for IndexConfig
type IndexConfig struct {
	IndexIVFFlatModel *IndexIVFFlatModel
	IndexIVFModel *IndexIVFModel
	IndexIVFPQModel *IndexIVFPQModel
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *IndexConfig) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into IndexIVFFlatModel
	err = json.Unmarshal(data, &dst.IndexIVFFlatModel);
	if err == nil {
		jsonIndexIVFFlatModel, _ := json.Marshal(dst.IndexIVFFlatModel)
		if string(jsonIndexIVFFlatModel) == "{}" { // empty struct
			dst.IndexIVFFlatModel = nil
		} else {
			return nil // data stored in dst.IndexIVFFlatModel, return on the first match
		}
	} else {
		dst.IndexIVFFlatModel = nil
	}

	// try to unmarshal JSON data into IndexIVFModel
	err = json.Unmarshal(data, &dst.IndexIVFModel);
	if err == nil {
		jsonIndexIVFModel, _ := json.Marshal(dst.IndexIVFModel)
		if string(jsonIndexIVFModel) == "{}" { // empty struct
			dst.IndexIVFModel = nil
		} else {
			return nil // data stored in dst.IndexIVFModel, return on the first match
		}
	} else {
		dst.IndexIVFModel = nil
	}

	// try to unmarshal JSON data into IndexIVFPQModel
	err = json.Unmarshal(data, &dst.IndexIVFPQModel);
	if err == nil {
		jsonIndexIVFPQModel, _ := json.Marshal(dst.IndexIVFPQModel)
		if string(jsonIndexIVFPQModel) == "{}" { // empty struct
			dst.IndexIVFPQModel = nil
		} else {
			return nil // data stored in dst.IndexIVFPQModel, return on the first match
		}
	} else {
		dst.IndexIVFPQModel = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(IndexConfig)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src IndexConfig) MarshalJSON() ([]byte, error) {
	if src.IndexIVFFlatModel != nil {
		return json.Marshal(&src.IndexIVFFlatModel)
	}

	if src.IndexIVFModel != nil {
		return json.Marshal(&src.IndexIVFModel)
	}

	if src.IndexIVFPQModel != nil {
		return json.Marshal(&src.IndexIVFPQModel)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableIndexConfig struct {
	value *IndexConfig
	isSet bool
}

func (v NullableIndexConfig) Get() *IndexConfig {
	return v.value
}

func (v *NullableIndexConfig) Set(val *IndexConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexConfig(val *IndexConfig) *NullableIndexConfig {
	return &NullableIndexConfig{value: val, isSet: true}
}

func (v NullableIndexConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


