/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListIDsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListIDsRequest{}

// ListIDsRequest Request model for listing all IDs in the index.  Inherits:     IndexOperationRequest: Includes `index_name` and `index_key`.
type ListIDsRequest struct {
	// 32-byte encryption key as hex string
	IndexKey string `json:"index_key"`
	// ID name
	IndexName string `json:"index_name"`
}

type _ListIDsRequest ListIDsRequest

// NewListIDsRequest instantiates a new ListIDsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListIDsRequest(indexKey string, indexName string) *ListIDsRequest {
	this := ListIDsRequest{}
	this.IndexKey = indexKey
	this.IndexName = indexName
	return &this
}

// NewListIDsRequestWithDefaults instantiates a new ListIDsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListIDsRequestWithDefaults() *ListIDsRequest {
	this := ListIDsRequest{}
	return &this
}

// GetIndexKey returns the IndexKey field value
func (o *ListIDsRequest) GetIndexKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexKey
}

// GetIndexKeyOk returns a tuple with the IndexKey field value
// and a boolean to check if the value has been set.
func (o *ListIDsRequest) GetIndexKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexKey, true
}

// SetIndexKey sets field value
func (o *ListIDsRequest) SetIndexKey(v string) {
	o.IndexKey = v
}

// GetIndexName returns the IndexName field value
func (o *ListIDsRequest) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *ListIDsRequest) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *ListIDsRequest) SetIndexName(v string) {
	o.IndexName = v
}

func (o ListIDsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListIDsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index_key"] = o.IndexKey
	toSerialize["index_name"] = o.IndexName
	return toSerialize, nil
}

func (o *ListIDsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index_key",
		"index_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListIDsRequest := _ListIDsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListIDsRequest)

	if err != nil {
		return err
	}

	*o = ListIDsRequest(varListIDsRequest)

	return err
}

type NullableListIDsRequest struct {
	value *ListIDsRequest
	isSet bool
}

func (v NullableListIDsRequest) Get() *ListIDsRequest {
	return v.value
}

func (v *NullableListIDsRequest) Set(val *ListIDsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListIDsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListIDsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIDsRequest(val *ListIDsRequest) *NullableListIDsRequest {
	return &NullableListIDsRequest{value: val, isSet: true}
}

func (v NullableListIDsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIDsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


