// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"fmt"
	"bytes"
)

// IndexIVFPQModel configures an IVFPQ (Inverted File with Product Quantization) index.
type IndexIVFPQModel struct {
	Dimension int32  `json:"dimension,omitempty"`
	NLists    int32   `json:"n_lists"`
	Metric    string `json:"metric,omitempty"`
	Type      string  `json:"type"`      // default: "ivfpq"
	PqDim     int32   `json:"pq_dim"`    // required
	PqBits    int32   `json:"pq_bits"`   // required
}

type _IndexIVFPQModel IndexIVFPQModel

// NewIndexIVFPQModel instantiates a new IVFPQ index model with required fields.
func NewIndexIVFPQModel(nLists int32, pqDim int32, pqBits int32) *IndexIVFPQModel {
	model := IndexIVFPQModel{
		NLists: nLists,
		Type:   "ivfpq",
		PqDim:  pqDim,
		PqBits: pqBits,
	}
	return &model
}

// NewIndexIVFPQModelWithDefaults instantiates a new IVFPQ model with only default values.
func NewIndexIVFPQModelWithDefaults() *IndexIVFPQModel {
	return &IndexIVFPQModel{
		Type: "ivfpq",
	}
}

func (o IndexIVFPQModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return nil, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexIVFPQModel) ToMap() (map[string]interface{}, error) {
	return map[string]interface{}{
		"dimension": o.Dimension,
		"n_lists":   o.NLists,
		"metric":    o.Metric,
		"type":      o.Type,
		"pq_dim":    o.PqDim,
		"pq_bits":   o.PqBits,
	}, nil
}

func (o *IndexIVFPQModel) UnmarshalJSON(data []byte) error {
	requiredProps := []string{"n_lists", "pq_dim", "pq_bits"}
	var allProps map[string]interface{}
	err := json.Unmarshal(data, &allProps)
	if err != nil {
		return err
	}

	for _, prop := range requiredProps {
		if _, found := allProps[prop]; !found {
			return fmt.Errorf("required field %s is missing", prop)
		}
	}

	var temp _IndexIVFPQModel
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&temp)
	if err != nil {
		return err
	}

	*o = IndexIVFPQModel(temp)

	// Ensure type defaults to "ivfpq" if not explicitly provided
	if o.Type == "" {
		o.Type = "ivfpq"
	}

	return nil
}

// Nullable wrapper
type NullableIndexIVFPQModel struct {
	value *IndexIVFPQModel
	isSet bool
}

func (v NullableIndexIVFPQModel) Get() *IndexIVFPQModel {
	return v.value
}

func (v *NullableIndexIVFPQModel) Set(val *IndexIVFPQModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexIVFPQModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexIVFPQModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexIVFPQModel(val *IndexIVFPQModel) *NullableIndexIVFPQModel {
	return &NullableIndexIVFPQModel{value: val, isSet: true}
}

func (v NullableIndexIVFPQModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexIVFPQModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (m *IndexIVFPQModel) isIndexModel() {}