/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.16.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BinaryUpsertRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BinaryUpsertRequest{}

// BinaryUpsertRequest Request model for adding or updating vectors using binary format.  This is more efficient than UpsertRequest for large batches as vectors are sent as base64-encoded binary data instead of JSON arrays.  Inherits:     IndexOperationRequest: Includes `index_name` and `index_key`.  Attributes:     batch (BinaryVectorBatch): The batch of vectors in binary format.
type BinaryUpsertRequest struct {
	// 32-byte encryption key as hex string
	IndexKey string `json:"index_key"`
	// ID name
	IndexName string `json:"index_name"`
	Batch BinaryVectorBatch `json:"batch"`
}

type _BinaryUpsertRequest BinaryUpsertRequest

// NewBinaryUpsertRequest instantiates a new BinaryUpsertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBinaryUpsertRequest(indexKey string, indexName string, batch BinaryVectorBatch) *BinaryUpsertRequest {
	this := BinaryUpsertRequest{}
	this.IndexKey = indexKey
	this.IndexName = indexName
	this.Batch = batch
	return &this
}

// NewBinaryUpsertRequestWithDefaults instantiates a new BinaryUpsertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBinaryUpsertRequestWithDefaults() *BinaryUpsertRequest {
	this := BinaryUpsertRequest{}
	return &this
}

// GetIndexKey returns the IndexKey field value
func (o *BinaryUpsertRequest) GetIndexKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexKey
}

// GetIndexKeyOk returns a tuple with the IndexKey field value
// and a boolean to check if the value has been set.
func (o *BinaryUpsertRequest) GetIndexKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexKey, true
}

// SetIndexKey sets field value
func (o *BinaryUpsertRequest) SetIndexKey(v string) {
	o.IndexKey = v
}

// GetIndexName returns the IndexName field value
func (o *BinaryUpsertRequest) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *BinaryUpsertRequest) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *BinaryUpsertRequest) SetIndexName(v string) {
	o.IndexName = v
}

// GetBatch returns the Batch field value
func (o *BinaryUpsertRequest) GetBatch() BinaryVectorBatch {
	if o == nil {
		var ret BinaryVectorBatch
		return ret
	}

	return o.Batch
}

// GetBatchOk returns a tuple with the Batch field value
// and a boolean to check if the value has been set.
func (o *BinaryUpsertRequest) GetBatchOk() (*BinaryVectorBatch, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Batch, true
}

// SetBatch sets field value
func (o *BinaryUpsertRequest) SetBatch(v BinaryVectorBatch) {
	o.Batch = v
}

func (o BinaryUpsertRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BinaryUpsertRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index_key"] = o.IndexKey
	toSerialize["index_name"] = o.IndexName
	toSerialize["batch"] = o.Batch
	return toSerialize, nil
}

func (o *BinaryUpsertRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index_key",
		"index_name",
		"batch",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBinaryUpsertRequest := _BinaryUpsertRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	
	err = decoder.Decode(&varBinaryUpsertRequest)

	if err != nil {
		return err
	}

	*o = BinaryUpsertRequest(varBinaryUpsertRequest)

	return err
}

type NullableBinaryUpsertRequest struct {
	value *BinaryUpsertRequest
	isSet bool
}

func (v NullableBinaryUpsertRequest) Get() *BinaryUpsertRequest {
	return v.value
}

func (v *NullableBinaryUpsertRequest) Set(val *BinaryUpsertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBinaryUpsertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBinaryUpsertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBinaryUpsertRequest(val *BinaryUpsertRequest) *NullableBinaryUpsertRequest {
	return &NullableBinaryUpsertRequest{value: val, isSet: true}
}

func (v NullableBinaryUpsertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBinaryUpsertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


