// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// IndexIVFPQModel configures an IVFPQ (Inverted File with Product Quantization) index.
// Changes:
// - Removed metric and n_lists
// - Made dimension optional
// - pq_dim and pq_bits remain required
type IndexIVFPQModel struct {
	Dimension *int32 `json:"dimension,omitempty"`
	Type      string `json:"type"`    // default: "ivfpq"
	PqDim     int32  `json:"pq_dim"`  // required
	PqBits    int32  `json:"pq_bits"` // required
}

type _IndexIVFPQModel IndexIVFPQModel

// NewIndexIVFPQModel instantiates a new IVFPQ index model with required fields.
func NewIndexIVFPQModel(pqDim int32, pqBits int32) *IndexIVFPQModel {
	return &IndexIVFPQModel{
		Type:   "ivfpq",
		PqDim:  pqDim,
		PqBits: pqBits,
	}
}

// NewIndexIVFPQModelWithDefaults instantiates a new IVFPQ model with only default values.
func NewIndexIVFPQModelWithDefaults() *IndexIVFPQModel {
	return &IndexIVFPQModel{
		Type: "ivfpq",
	}
}

// GetDimension returns the Dimension value if set, zero value otherwise.
func (o *IndexIVFPQModel) GetDimension() int32 {
	if o == nil || o.Dimension == nil {
		var ret int32
		return ret
	}
	return *o.Dimension
}

// GetDimensionOk returns a tuple with the Dimension field value (if set) and a boolean.
func (o *IndexIVFPQModel) GetDimensionOk() (*int32, bool) {
	if o == nil || o.Dimension == nil {
		return nil, false
	}
	return o.Dimension, true
}

// HasDimension checks if Dimension was set.
func (o *IndexIVFPQModel) HasDimension() bool {
	return o != nil && o.Dimension != nil
}

// SetDimension assigns the given int32 to Dimension.
func (o *IndexIVFPQModel) SetDimension(v int32) {
	o.Dimension = &v
}

func (o IndexIVFPQModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return nil, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexIVFPQModel) ToMap() (map[string]interface{}, error) {
	m := map[string]interface{}{
		"type":    o.Type,
		"pq_dim":  o.PqDim,
		"pq_bits": o.PqBits,
	}
	if o.Dimension != nil {
		m["dimension"] = *o.Dimension
	}
	return m, nil
}

func (o *IndexIVFPQModel) UnmarshalJSON(data []byte) error {
	requiredProps := []string{"pq_dim", "pq_bits"}
	var allProps map[string]interface{}
	if err := json.Unmarshal(data, &allProps); err != nil {
		return err
	}
	for _, prop := range requiredProps {
		if _, found := allProps[prop]; !found {
			return fmt.Errorf("required field %s is missing", prop)
		}
	}

	var temp _IndexIVFPQModel
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&temp); err != nil {
		return err
	}

	*o = IndexIVFPQModel(temp)

	// Ensure type defaults to "ivfpq" if not explicitly provided
	if o.Type == "" {
		o.Type = "ivfpq"
	}
	return nil
}

// Nullable wrapper
type NullableIndexIVFPQModel struct {
	value *IndexIVFPQModel
	isSet bool
}

func (v NullableIndexIVFPQModel) Get() *IndexIVFPQModel {
	return v.value
}

func (v *NullableIndexIVFPQModel) Set(val *IndexIVFPQModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexIVFPQModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexIVFPQModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexIVFPQModel(val *IndexIVFPQModel) *NullableIndexIVFPQModel {
	return &NullableIndexIVFPQModel{value: val, isSet: true}
}

func (v NullableIndexIVFPQModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexIVFPQModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (m *IndexIVFPQModel) isIndexModel() {}
