/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateIndexRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateIndexRequest{}

// CreateIndexRequest Request model for creating a new encrypted index.  Attributes:     index_config (Optional[Union[IndexIVFModel, IndexIVFPQModel, IndexIVFFlatModel]]):          Optional configuration model for the index.     index_key (str): A 32-byte encryption key as a hex string.     index_name (str): The name/identifier of the index.     embedding_model (Optional[str]): Optional embedding model name.     metric (Optional[str]): Optional distance metric.
type CreateIndexRequest struct {
	IndexConfig NullableIndexConfig `json:"index_config,omitempty"`
	// 32-byte encryption key as hex string
	IndexKey string `json:"index_key"`
	// ID name
	IndexName string `json:"index_name"`
	EmbeddingModel NullableString `json:"embedding_model,omitempty"`
	Metric NullableString `json:"metric,omitempty"`
}

type _CreateIndexRequest CreateIndexRequest

// NewCreateIndexRequest instantiates a new CreateIndexRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateIndexRequest(indexKey string, indexName string) *CreateIndexRequest {
	this := CreateIndexRequest{}
	this.IndexKey = indexKey
	this.IndexName = indexName
	return &this
}

// NewCreateIndexRequestWithDefaults instantiates a new CreateIndexRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateIndexRequestWithDefaults() *CreateIndexRequest {
	this := CreateIndexRequest{}
	return &this
}

// GetIndexConfig returns the IndexConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateIndexRequest) GetIndexConfig() IndexConfig {
	if o == nil || IsNil(o.IndexConfig.Get()) {
		var ret IndexConfig
		return ret
	}
	return *o.IndexConfig.Get()
}

// GetIndexConfigOk returns a tuple with the IndexConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateIndexRequest) GetIndexConfigOk() (*IndexConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.IndexConfig.Get(), o.IndexConfig.IsSet()
}

// HasIndexConfig returns a boolean if a field has been set.
func (o *CreateIndexRequest) HasIndexConfig() bool {
	if o != nil && o.IndexConfig.IsSet() {
		return true
	}

	return false
}

// SetIndexConfig gets a reference to the given NullableIndexConfig and assigns it to the IndexConfig field.
func (o *CreateIndexRequest) SetIndexConfig(v IndexConfig) {
	o.IndexConfig.Set(&v)
}
// SetIndexConfigNil sets the value for IndexConfig to be an explicit nil
func (o *CreateIndexRequest) SetIndexConfigNil() {
	o.IndexConfig.Set(nil)
}

// UnsetIndexConfig ensures that no value is present for IndexConfig, not even an explicit nil
func (o *CreateIndexRequest) UnsetIndexConfig() {
	o.IndexConfig.Unset()
}

// GetIndexKey returns the IndexKey field value
func (o *CreateIndexRequest) GetIndexKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexKey
}

// GetIndexKeyOk returns a tuple with the IndexKey field value
// and a boolean to check if the value has been set.
func (o *CreateIndexRequest) GetIndexKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexKey, true
}

// SetIndexKey sets field value
func (o *CreateIndexRequest) SetIndexKey(v string) {
	o.IndexKey = v
}

// GetIndexName returns the IndexName field value
func (o *CreateIndexRequest) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *CreateIndexRequest) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *CreateIndexRequest) SetIndexName(v string) {
	o.IndexName = v
}

// GetEmbeddingModel returns the EmbeddingModel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateIndexRequest) GetEmbeddingModel() string {
	if o == nil || IsNil(o.EmbeddingModel.Get()) {
		var ret string
		return ret
	}
	return *o.EmbeddingModel.Get()
}

// GetEmbeddingModelOk returns a tuple with the EmbeddingModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateIndexRequest) GetEmbeddingModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmbeddingModel.Get(), o.EmbeddingModel.IsSet()
}

// HasEmbeddingModel returns a boolean if a field has been set.
func (o *CreateIndexRequest) HasEmbeddingModel() bool {
	if o != nil && o.EmbeddingModel.IsSet() {
		return true
	}

	return false
}

// SetEmbeddingModel gets a reference to the given NullableString and assigns it to the EmbeddingModel field.
func (o *CreateIndexRequest) SetEmbeddingModel(v string) {
	o.EmbeddingModel.Set(&v)
}
// SetEmbeddingModelNil sets the value for EmbeddingModel to be an explicit nil
func (o *CreateIndexRequest) SetEmbeddingModelNil() {
	o.EmbeddingModel.Set(nil)
}

// UnsetEmbeddingModel ensures that no value is present for EmbeddingModel, not even an explicit nil
func (o *CreateIndexRequest) UnsetEmbeddingModel() {
	o.EmbeddingModel.Unset()
}

// GetMetric returns the Metric field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateIndexRequest) GetMetric() string {
	if o == nil || IsNil(o.Metric.Get()) {
		var ret string
		return ret
	}
	return *o.Metric.Get()
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateIndexRequest) GetMetricOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Metric.Get(), o.Metric.IsSet()
}

// HasMetric returns a boolean if a field has been set.
func (o *CreateIndexRequest) HasMetric() bool {
	if o != nil && o.Metric.IsSet() {
		return true
	}

	return false
}

// SetMetric gets a reference to the given NullableString and assigns it to the Metric field.
func (o *CreateIndexRequest) SetMetric(v string) {
	o.Metric.Set(&v)
}
// SetMetricNil sets the value for Metric to be an explicit nil
func (o *CreateIndexRequest) SetMetricNil() {
	o.Metric.Set(nil)
}

// UnsetMetric ensures that no value is present for Metric, not even an explicit nil
func (o *CreateIndexRequest) UnsetMetric() {
	o.Metric.Unset()
}

func (o CreateIndexRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateIndexRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.IndexConfig.IsSet() {
		toSerialize["index_config"] = o.IndexConfig.Get()
	}
	toSerialize["index_key"] = o.IndexKey
	toSerialize["index_name"] = o.IndexName
	if o.EmbeddingModel.IsSet() {
		toSerialize["embedding_model"] = o.EmbeddingModel.Get()
	}
	if o.Metric.IsSet() {
		toSerialize["metric"] = o.Metric.Get()
	}
	return toSerialize, nil
}

func (o *CreateIndexRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index_key",
		"index_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateIndexRequest := _CreateIndexRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateIndexRequest)

	if err != nil {
		return err
	}

	*o = CreateIndexRequest(varCreateIndexRequest)

	return err
}

type NullableCreateIndexRequest struct {
	value *CreateIndexRequest
	isSet bool
}

func (v NullableCreateIndexRequest) Get() *CreateIndexRequest {
	return v.value
}

func (v *NullableCreateIndexRequest) Set(val *CreateIndexRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIndexRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIndexRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIndexRequest(val *CreateIndexRequest) *NullableCreateIndexRequest {
	return &NullableCreateIndexRequest{value: val, isSet: true}
}

func (v NullableCreateIndexRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIndexRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


