/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IndexConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexConfig{}

// IndexConfig struct for IndexConfig
// Notes:
// - metric removed
// - n_lists removed
// - dimension is now optional
type IndexConfig struct {
	Dimension *int32 `json:"dimension,omitempty"`
	IndexType string `json:"index_type"`
	PqDim     *int32 `json:"pq_dim,omitempty"`
	PqBits    *int32 `json:"pq_bits,omitempty"`
}

type _IndexConfig IndexConfig

// NewIndexConfig instantiates a new IndexConfig object with required fields only.
// Since dimension is optional now, it is not a constructor parameter.
func NewIndexConfig(indexType string) *IndexConfig {
	this := IndexConfig{}
	this.IndexType = indexType
	return &this
}

// NewIndexConfigWithDefaults instantiates a new IndexConfig object
// assigning only default values (no required fields are guaranteed to be set).
func NewIndexConfigWithDefaults() *IndexConfig {
	this := IndexConfig{}
	return &this
}

// GetDimension returns the Dimension field value if set, zero value otherwise.
func (o *IndexConfig) GetDimension() int32 {
	if o == nil || IsNil(o.Dimension) {
		var ret int32
		return ret
	}
	return *o.Dimension
}

// GetDimensionOk returns a tuple with the Dimension field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexConfig) GetDimensionOk() (*int32, bool) {
	if o == nil || IsNil(o.Dimension) {
		return nil, false
	}
	return o.Dimension, true
}

// HasDimension returns a boolean if the Dimension field has been set.
func (o *IndexConfig) HasDimension() bool {
	return o != nil && !IsNil(o.Dimension)
}

// SetDimension gets a reference to the given int32 and assigns it to the Dimension field.
func (o *IndexConfig) SetDimension(v int32) {
	o.Dimension = &v
}

// GetIndexType returns the IndexType field value
func (o *IndexConfig) GetIndexType() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.IndexType
}

// GetIndexTypeOk returns a tuple with the IndexType field value
// and a boolean to check if the value has been set.
func (o *IndexConfig) GetIndexTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexType, true
}

// SetIndexType sets field value
func (o *IndexConfig) SetIndexType(v string) {
	o.IndexType = v
}

// GetPqDim returns the PqDim field value if set, zero value otherwise.
func (o *IndexConfig) GetPqDim() int32 {
	if o == nil || IsNil(o.PqDim) {
		var ret int32
		return ret
	}
	return *o.PqDim
}

// GetPqDimOk returns a tuple with the PqDim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexConfig) GetPqDimOk() (*int32, bool) {
	if o == nil || IsNil(o.PqDim) {
		return nil, false
	}
	return o.PqDim, true
}

// HasPqDim returns a boolean if a field has been set.
func (o *IndexConfig) HasPqDim() bool {
	return o != nil && !IsNil(o.PqDim)
}

// SetPqDim gets a reference to the given int32 and assigns it to the PqDim field.
func (o *IndexConfig) SetPqDim(v int32) {
	o.PqDim = &v
}

// GetPqBits returns the PqBits field value if set, zero value otherwise.
func (o *IndexConfig) GetPqBits() int32 {
	if o == nil || IsNil(o.PqBits) {
		var ret int32
		return ret
	}
	return *o.PqBits
}

// GetPqBitsOk returns a tuple with the PqBits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexConfig) GetPqBitsOk() (*int32, bool) {
	if o == nil || IsNil(o.PqBits) {
		return nil, false
	}
	return o.PqBits, true
}

// HasPqBits returns a boolean if a field has been set.
func (o *IndexConfig) HasPqBits() bool {
	return o != nil && !IsNil(o.PqBits)
}

// SetPqBits gets a reference to the given int32 and assigns it to the PqBits field.
func (o *IndexConfig) SetPqBits(v int32) {
	o.PqBits = &v
}

func (cfg IndexConfig) MarshalJSON() ([]byte, error) {
	// API payload uses "type" (for index type)
	data := map[string]interface{}{
		"type": cfg.IndexType,
	}

	if cfg.Dimension != nil {
		data["dimension"] = *cfg.Dimension
	}
	if cfg.PqDim != nil {
		data["pq_dim"] = *cfg.PqDim
	}
	if cfg.PqBits != nil {
		data["pq_bits"] = *cfg.PqBits
	}

	return json.Marshal(data)
}

func (o IndexConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dimension) {
		toSerialize["dimension"] = o.Dimension
	}
	toSerialize["index_type"] = o.IndexType
	if !IsNil(o.PqDim) {
		toSerialize["pq_dim"] = o.PqDim
	}
	if !IsNil(o.PqBits) {
		toSerialize["pq_bits"] = o.PqBits
	}
	return toSerialize, nil
}

func (o *IndexConfig) UnmarshalJSON(data []byte) (err error) {
	// Validate that required properties are present.
	requiredProperties := []string{
		"index_type",
	}

	allProperties := make(map[string]interface{})
	if err = json.Unmarshal(data, &allProperties); err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIndexConfig := _IndexConfig{}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&varIndexConfig); err != nil {
		return err
	}

	*o = IndexConfig(varIndexConfig)
	return nil
}

type NullableIndexConfig struct {
	value *IndexConfig
	isSet bool
}

func (v NullableIndexConfig) Get() *IndexConfig {
	return v.value
}

func (v *NullableIndexConfig) Set(val *IndexConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexConfig(val *IndexConfig) *NullableIndexConfig {
	return &NullableIndexConfig{value: val, isSet: true}
}

func (v NullableIndexConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
