/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IndexIVFPQModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexIVFPQModel{}

// IndexIVFPQModel Model for configuring an IVFPQ (Inverted File with Product Quantization) index.  Attributes:     type (str): Index type identifier. Defaults to \"ivfpq\".     pq_dim (int): Dimensionality of PQ codes.     pq_bits (int): Number of bits per quantizer.
type IndexIVFPQModel struct {
	Dimension NullableInt32 `json:"dimension,omitempty"`
	Type *string `json:"type,omitempty"`
	PqDim int32 `json:"pq_dim"`
	PqBits int32 `json:"pq_bits"`
}

type _IndexIVFPQModel IndexIVFPQModel

// NewIndexIVFPQModel instantiates a new IndexIVFPQModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexIVFPQModel(pqDim int32, pqBits int32) *IndexIVFPQModel {
	this := IndexIVFPQModel{}
	var type_ string = "ivfpq"
	this.Type = &type_
	this.PqDim = pqDim
	this.PqBits = pqBits
	return &this
}

// NewIndexIVFPQModelWithDefaults instantiates a new IndexIVFPQModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexIVFPQModelWithDefaults() *IndexIVFPQModel {
	this := IndexIVFPQModel{}
	var type_ string = "ivfpq"
	this.Type = &type_
	return &this
}

// GetDimension returns the Dimension field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexIVFPQModel) GetDimension() int32 {
	if o == nil || IsNil(o.Dimension.Get()) {
		var ret int32
		return ret
	}
	return *o.Dimension.Get()
}

// GetDimensionOk returns a tuple with the Dimension field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexIVFPQModel) GetDimensionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dimension.Get(), o.Dimension.IsSet()
}

// HasDimension returns a boolean if a field has been set.
func (o *IndexIVFPQModel) HasDimension() bool {
	if o != nil && o.Dimension.IsSet() {
		return true
	}

	return false
}

// SetDimension gets a reference to the given NullableInt32 and assigns it to the Dimension field.
func (o *IndexIVFPQModel) SetDimension(v int32) {
	o.Dimension.Set(&v)
}
// SetDimensionNil sets the value for Dimension to be an explicit nil
func (o *IndexIVFPQModel) SetDimensionNil() {
	o.Dimension.Set(nil)
}

// UnsetDimension ensures that no value is present for Dimension, not even an explicit nil
func (o *IndexIVFPQModel) UnsetDimension() {
	o.Dimension.Unset()
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IndexIVFPQModel) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexIVFPQModel) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IndexIVFPQModel) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IndexIVFPQModel) SetType(v string) {
	o.Type = &v
}

// GetPqDim returns the PqDim field value
func (o *IndexIVFPQModel) GetPqDim() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PqDim
}

// GetPqDimOk returns a tuple with the PqDim field value
// and a boolean to check if the value has been set.
func (o *IndexIVFPQModel) GetPqDimOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PqDim, true
}

// SetPqDim sets field value
func (o *IndexIVFPQModel) SetPqDim(v int32) {
	o.PqDim = v
}

// GetPqBits returns the PqBits field value
func (o *IndexIVFPQModel) GetPqBits() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PqBits
}

// GetPqBitsOk returns a tuple with the PqBits field value
// and a boolean to check if the value has been set.
func (o *IndexIVFPQModel) GetPqBitsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PqBits, true
}

// SetPqBits sets field value
func (o *IndexIVFPQModel) SetPqBits(v int32) {
	o.PqBits = v
}

func (o IndexIVFPQModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexIVFPQModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Dimension.IsSet() {
		toSerialize["dimension"] = o.Dimension.Get()
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["pq_dim"] = o.PqDim
	toSerialize["pq_bits"] = o.PqBits
	return toSerialize, nil
}

func (o *IndexIVFPQModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pq_dim",
		"pq_bits",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIndexIVFPQModel := _IndexIVFPQModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIndexIVFPQModel)

	if err != nil {
		return err
	}

	*o = IndexIVFPQModel(varIndexIVFPQModel)

	return err
}

type NullableIndexIVFPQModel struct {
	value *IndexIVFPQModel
	isSet bool
}

func (v NullableIndexIVFPQModel) Get() *IndexIVFPQModel {
	return v.value
}

func (v *NullableIndexIVFPQModel) Set(val *IndexIVFPQModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexIVFPQModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexIVFPQModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexIVFPQModel(val *IndexIVFPQModel) *NullableIndexIVFPQModel {
	return &NullableIndexIVFPQModel{value: val, isSet: true}
}

func (v NullableIndexIVFPQModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexIVFPQModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


