// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"bytes"
	"encoding/json"
)

// IndexIVFFlatModel configures an IVFFlat (Inverted File with Flat quantization) index.
// Changes:
// - Removed metric and n_lists
// - Dimension remains optional
type IndexIVFFlatModel struct {
	Dimension *int32 `json:"dimension,omitempty"`
	Type      string `json:"type"` // default: "ivfflat"
}

type _IndexIVFFlatModel IndexIVFFlatModel

// NewIndexIVFFlatModel creates a new IVFFlat index model with default type set.
func NewIndexIVFFlatModel() *IndexIVFFlatModel {
	return &IndexIVFFlatModel{
		Type: "ivfflat",
	}
}

// NewIndexIVFFlatModelWithDefaults creates a new IVFFlat index model with default type set.
func NewIndexIVFFlatModelWithDefaults() *IndexIVFFlatModel {
	return &IndexIVFFlatModel{
		Type: "ivfflat",
	}
}

// GetDimension returns the Dimension value if set, zero value otherwise.
func (o *IndexIVFFlatModel) GetDimension() int32 {
	if o == nil || o.Dimension == nil {
		var ret int32
		return ret
	}
	return *o.Dimension
}

// GetDimensionOk returns a tuple with the Dimension field value (if set) and a boolean.
func (o *IndexIVFFlatModel) GetDimensionOk() (*int32, bool) {
	if o == nil || o.Dimension == nil {
		return nil, false
	}
	return o.Dimension, true
}

// HasDimension checks if Dimension was set.
func (o *IndexIVFFlatModel) HasDimension() bool {
	return o != nil && o.Dimension != nil
}

// SetDimension assigns the given int32 to Dimension.
func (o *IndexIVFFlatModel) SetDimension(v int32) {
	o.Dimension = &v
}

func (o IndexIVFFlatModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return nil, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexIVFFlatModel) ToMap() (map[string]interface{}, error) {
	m := map[string]interface{}{
		"type": o.Type,
	}
	if o.Dimension != nil {
		m["dimension"] = *o.Dimension
	}
	return m, nil
}

func (o *IndexIVFFlatModel) UnmarshalJSON(data []byte) error {
	var temp _IndexIVFFlatModel
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&temp); err != nil {
		return err
	}
	*o = IndexIVFFlatModel(temp)

	if o.Type == "" {
		o.Type = "ivfflat"
	}
	return nil
}

type NullableIndexIVFFlatModel struct {
	value *IndexIVFFlatModel
	isSet bool
}

func (v NullableIndexIVFFlatModel) Get() *IndexIVFFlatModel {
	return v.value
}

func (v *NullableIndexIVFFlatModel) Set(val *IndexIVFFlatModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexIVFFlatModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexIVFFlatModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexIVFFlatModel(val *IndexIVFFlatModel) *NullableIndexIVFFlatModel {
	return &NullableIndexIVFFlatModel{value: val, isSet: true}
}

func (v NullableIndexIVFFlatModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexIVFFlatModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (m *IndexIVFFlatModel) isIndexModel() {}
