// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateIndexRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateIndexRequest{}

// CreateIndexRequest struct for CreateIndexRequest
type CreateIndexRequest struct {
	IndexName      string       `json:"index_name"`
	IndexKey       string       `json:"index_key"`
	IndexConfig    *IndexConfig `json:"index_config,omitempty"`
	EmbeddingModel *string      `json:"embedding_model,omitempty"`
	Metric         *string      `json:"metric,omitempty"`         // already optional metric
}

type _CreateIndexRequest CreateIndexRequest

// NewCreateIndexRequest instantiates a new CreateIndexRequest with required fields only
func NewCreateIndexRequest(indexName string, indexKey string) *CreateIndexRequest {
	this := CreateIndexRequest{}
	this.IndexName = indexName
	this.IndexKey = indexKey
	return &this
}

// NewCreateIndexRequestWithDefaults instantiates with only defaults
func NewCreateIndexRequestWithDefaults() *CreateIndexRequest {
	this := CreateIndexRequest{}
	return &this
}

// GetIndexName returns the IndexName field value
func (o *CreateIndexRequest) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.IndexName
}

func (o *CreateIndexRequest) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

func (o *CreateIndexRequest) SetIndexName(v string) {
	o.IndexName = v
}

// GetIndexKey returns the IndexKey field value
func (o *CreateIndexRequest) GetIndexKey() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.IndexKey
}

func (o *CreateIndexRequest) GetIndexKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexKey, true
}

func (o *CreateIndexRequest) SetIndexKey(v string) {
	o.IndexKey = v
}

// Optional IndexConfig helpers
func (o *CreateIndexRequest) GetIndexConfig() IndexConfig {
	if o == nil || o.IndexConfig == nil {
		var ret IndexConfig
		return ret
	}
	return *o.IndexConfig
}

func (o *CreateIndexRequest) GetIndexConfigOk() (*IndexConfig, bool) {
	if o == nil || o.IndexConfig == nil {
		return nil, false
	}
	return o.IndexConfig, true
}

func (o *CreateIndexRequest) HasIndexConfig() bool {
	return o != nil && o.IndexConfig != nil
}

func (o *CreateIndexRequest) SetIndexConfig(v IndexConfig) {
	o.IndexConfig = &v
}

// Optional Metric helpers
func (o *CreateIndexRequest) GetMetric() string {
	if o == nil || o.Metric == nil {
		var ret string
		return ret
	}
	return *o.Metric
}

func (o *CreateIndexRequest) GetMetricOk() (*string, bool) {
	if o == nil || o.Metric == nil {
		return nil, false
	}
	return o.Metric, true
}

func (o *CreateIndexRequest) HasMetric() bool {
	return o != nil && o.Metric != nil
}

func (o *CreateIndexRequest) SetMetric(v string) {
	o.Metric = &v
}

func (o CreateIndexRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateIndexRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index_name"] = o.IndexName
	toSerialize["index_key"] = o.IndexKey
	if o.IndexConfig != nil {
		toSerialize["index_config"] = o.IndexConfig
	}
	if o.EmbeddingModel != nil {
		toSerialize["embedding_model"] = o.EmbeddingModel
	}
	if o.Metric != nil {
		toSerialize["metric"] = o.Metric
	}
	return toSerialize, nil
}

func (o *CreateIndexRequest) UnmarshalJSON(data []byte) (err error) {
	// Only index_name and index_key are required now
	requiredProperties := []string{
		"index_name",
		"index_key",
	}

	allProperties := make(map[string]interface{})
	if err = json.Unmarshal(data, &allProperties); err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateIndexRequest := _CreateIndexRequest{}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&varCreateIndexRequest); err != nil {
		return err
	}

	*o = CreateIndexRequest(varCreateIndexRequest)
	return err
}

type NullableCreateIndexRequest struct {
	value *CreateIndexRequest
	isSet bool
}

func (v NullableCreateIndexRequest) Get() *CreateIndexRequest {
	return v.value
}

func (v *NullableCreateIndexRequest) Set(val *CreateIndexRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIndexRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIndexRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIndexRequest(val *CreateIndexRequest) *NullableCreateIndexRequest {
	return &NullableCreateIndexRequest{value: val, isSet: true}
}

func (v NullableCreateIndexRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIndexRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
