/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListIDsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListIDsResponse{}

// ListIDsResponse Response model for listing all IDs in the index.  Attributes:     ids (List[str]): List of all item IDs in the index.     count (int): Total number of IDs in the index.
type ListIDsResponse struct {
	Ids []string `json:"ids"`
	Count int32 `json:"count"`
}

type _ListIDsResponse ListIDsResponse

// NewListIDsResponse instantiates a new ListIDsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListIDsResponse(ids []string, count int32) *ListIDsResponse {
	this := ListIDsResponse{}
	this.Ids = ids
	this.Count = count
	return &this
}

// NewListIDsResponseWithDefaults instantiates a new ListIDsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListIDsResponseWithDefaults() *ListIDsResponse {
	this := ListIDsResponse{}
	return &this
}

// GetIds returns the Ids field value
func (o *ListIDsResponse) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *ListIDsResponse) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *ListIDsResponse) SetIds(v []string) {
	o.Ids = v
}

// GetCount returns the Count field value
func (o *ListIDsResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ListIDsResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ListIDsResponse) SetCount(v int32) {
	o.Count = v
}

func (o ListIDsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListIDsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ids"] = o.Ids
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *ListIDsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ids",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListIDsResponse := _ListIDsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListIDsResponse)

	if err != nil {
		return err
	}

	*o = ListIDsResponse(varListIDsResponse)

	return err
}

type NullableListIDsResponse struct {
	value *ListIDsResponse
	isSet bool
}

func (v NullableListIDsResponse) Get() *ListIDsResponse {
	return v.value
}

func (v *NullableListIDsResponse) Set(val *ListIDsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListIDsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListIDsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIDsResponse(val *ListIDsResponse) *NullableListIDsResponse {
	return &NullableListIDsResponse{value: val, isSet: true}
}

func (v NullableListIDsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIDsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


