/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchQueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchQueryRequest{}

// BatchQueryRequest struct for BatchQueryRequest
// Request model for batch similarity search.
// Inherits IndexOperationRequest: Includes `index_name` and `index_key`.
// Attributes:
//   - query_vectors ([][]float32): List of vectors to search for in batch mode.
//   - top_k (int32): Number of nearest neighbors to return for each query. Defaults to 100.
//   - n_probes (int32): Number of lists to probe during the query. Defaults to 1.
//   - greedy (bool): Whether to use greedy search. Defaults to false.
//   - filters (map[string]interface{}): JSON-like dictionary specifying metadata filters. Defaults to {}.
//   - include ([]string): List of additional fields to include in the response. Defaults to ["distances"].
type BatchQueryRequest struct {
	// 32-byte encryption key as hex string
	IndexKey string `json:"index_key"`
	// ID name
	IndexName string `json:"index_name"`
	// List of vectors to search for in batch mode
	QueryVectors [][]float32 `json:"query_vectors"`
	// Number of nearest neighbors to return for each query
	TopK *int32 `json:"top_k,omitempty"`
	// Number of lists to probe during the query
	NProbes *int32 `json:"n_probes,omitempty"`
	// Whether to use greedy search
	Greedy *bool `json:"greedy,omitempty"`
	// JSON-like dictionary specifying metadata filters
	Filters map[string]interface{} `json:"filters,omitempty"`
	// List of additional fields to include in the response
	Include []string `json:"include,omitempty"`
}

type _BatchQueryRequest BatchQueryRequest

// NewBatchQueryRequest instantiates a new BatchQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchQueryRequest(indexName string, indexKey string, queryVectors [][]float32) *BatchQueryRequest {
	this := BatchQueryRequest{}
	this.IndexName = indexName
	this.IndexKey = indexKey
	this.QueryVectors = queryVectors
	var topK int32 = 100
	this.TopK = &topK
	var nProbes int32 = 1
	this.NProbes = &nProbes
	var greedy bool = false
	this.Greedy = &greedy
	return &this
}

// NewBatchQueryRequestWithDefaults instantiates a new BatchQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchQueryRequestWithDefaults() *BatchQueryRequest {
	this := BatchQueryRequest{}
	var topK int32 = 100
	this.TopK = &topK
	var nProbes int32 = 1
	this.NProbes = &nProbes
	var greedy bool = false
	this.Greedy = &greedy
	return &this
}

// GetIndexName returns the IndexName field value
func (o *BatchQueryRequest) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *BatchQueryRequest) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *BatchQueryRequest) SetIndexName(v string) {
	o.IndexName = v
}

// GetIndexKey returns the IndexKey field value
func (o *BatchQueryRequest) GetIndexKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexKey
}

// GetIndexKeyOk returns a tuple with the IndexKey field value
// and a boolean to check if the value has been set.
func (o *BatchQueryRequest) GetIndexKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexKey, true
}

// SetIndexKey sets field value
func (o *BatchQueryRequest) SetIndexKey(v string) {
	o.IndexKey = v
}

// GetQueryVectors returns the QueryVectors field value
func (o *BatchQueryRequest) GetQueryVectors() [][]float32 {
	if o == nil {
		var ret [][]float32
		return ret
	}

	return o.QueryVectors
}

// GetQueryVectorsOk returns a tuple with the QueryVectors field value
// and a boolean to check if the value has been set.
func (o *BatchQueryRequest) GetQueryVectorsOk() ([][]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueryVectors, true
}

// SetQueryVectors sets field value
func (o *BatchQueryRequest) SetQueryVectors(v [][]float32) {
	o.QueryVectors = v
}

// GetTopK returns the TopK field value if set, zero value otherwise.
func (o *BatchQueryRequest) GetTopK() int32 {
	if o == nil || IsNil(o.TopK) {
		var ret int32
		return ret
	}
	return *o.TopK
}

// GetTopKOk returns a tuple with the TopK field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchQueryRequest) GetTopKOk() (*int32, bool) {
	if o == nil || IsNil(o.TopK) {
		return nil, false
	}
	return o.TopK, true
}

// HasTopK returns a boolean if a field has been set.
func (o *BatchQueryRequest) HasTopK() bool {
	if o != nil && !IsNil(o.TopK) {
		return true
	}

	return false
}

// SetTopK gets a reference to the given int32 and assigns it to the TopK field.
func (o *BatchQueryRequest) SetTopK(v int32) {
	o.TopK = &v
}

// GetNProbes returns the NProbes field value if set, zero value otherwise.
func (o *BatchQueryRequest) GetNProbes() int32 {
	if o == nil || IsNil(o.NProbes) {
		var ret int32
		return ret
	}
	return *o.NProbes
}

// GetNProbesOk returns a tuple with the NProbes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchQueryRequest) GetNProbesOk() (*int32, bool) {
	if o == nil || IsNil(o.NProbes) {
		return nil, false
	}
	return o.NProbes, true
}

// HasNProbes returns a boolean if a field has been set.
func (o *BatchQueryRequest) HasNProbes() bool {
	if o != nil && !IsNil(o.NProbes) {
		return true
	}

	return false
}

// SetNProbes gets a reference to the given int32 and assigns it to the NProbes field.
func (o *BatchQueryRequest) SetNProbes(v int32) {
	o.NProbes = &v
}

// GetGreedy returns the Greedy field value if set, zero value otherwise.
func (o *BatchQueryRequest) GetGreedy() bool {
	if o == nil || IsNil(o.Greedy) {
		var ret bool
		return ret
	}
	return *o.Greedy
}

// GetGreedyOk returns a tuple with the Greedy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchQueryRequest) GetGreedyOk() (*bool, bool) {
	if o == nil || IsNil(o.Greedy) {
		return nil, false
	}
	return o.Greedy, true
}

// HasGreedy returns a boolean if a field has been set.
func (o *BatchQueryRequest) HasGreedy() bool {
	if o != nil && !IsNil(o.Greedy) {
		return true
	}

	return false
}

// SetGreedy gets a reference to the given bool and assigns it to the Greedy field.
func (o *BatchQueryRequest) SetGreedy(v bool) {
	o.Greedy = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *BatchQueryRequest) GetFilters() map[string]interface{} {
	if o == nil || IsNil(o.Filters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchQueryRequest) GetFiltersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filters) {
		return map[string]interface{}{}, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *BatchQueryRequest) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given map[string]interface{} and assigns it to the Filters field.
func (o *BatchQueryRequest) SetFilters(v map[string]interface{}) {
	o.Filters = v
}

// GetInclude returns the Include field value if set, zero value otherwise.
func (o *BatchQueryRequest) GetInclude() []string {
	if o == nil || IsNil(o.Include) {
		var ret []string
		return ret
	}
	return o.Include
}

// GetIncludeOk returns a tuple with the Include field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchQueryRequest) GetIncludeOk() ([]string, bool) {
	if o == nil || IsNil(o.Include) {
		return nil, false
	}
	return o.Include, true
}

// HasInclude returns a boolean if a field has been set.
func (o *BatchQueryRequest) HasInclude() bool {
	if o != nil && !IsNil(o.Include) {
		return true
	}

	return false
}

// SetInclude gets a reference to the given []string and assigns it to the Include field.
func (o *BatchQueryRequest) SetInclude(v []string) {
	o.Include = v
}

func (o BatchQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchQueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index_name"] = o.IndexName
	toSerialize["index_key"] = o.IndexKey
	toSerialize["query_vectors"] = o.QueryVectors
	if !IsNil(o.TopK) {
		toSerialize["top_k"] = o.TopK
	}
	if !IsNil(o.NProbes) {
		toSerialize["n_probes"] = o.NProbes
	}
	if !IsNil(o.Greedy) {
		toSerialize["greedy"] = o.Greedy
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.Include) {
		toSerialize["include"] = o.Include
	}
	return toSerialize, nil
}

func (o *BatchQueryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index_name",
		"index_key",
		"query_vectors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchQueryRequest := _BatchQueryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchQueryRequest)

	if err != nil {
		return err
	}

	*o = BatchQueryRequest(varBatchQueryRequest)

	return err
}

type NullableBatchQueryRequest struct {
	value *BatchQueryRequest
	isSet bool
}

func (v NullableBatchQueryRequest) Get() *BatchQueryRequest {
	return v.value
}

func (v *NullableBatchQueryRequest) Set(val *BatchQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchQueryRequest(val *BatchQueryRequest) *NullableBatchQueryRequest {
	return &NullableBatchQueryRequest{value: val, isSet: true}
}

func (v NullableBatchQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
