/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IndexInfoResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexInfoResponseModel{}

// IndexInfoResponseModel Response model for retrieving information about an index.  Attributes:     index_name (str): The name of the index.     index_type (str): The type of index (e.g., IVF, IVFFlat, IVFPQ).     is_trained (bool): Indicates whether the index has been trained.     index_config (Dict[str, Any]): The full configuration details of the index.
type IndexInfoResponseModel struct {
	IndexName string `json:"index_name"`
	IndexType string `json:"index_type"`
	IsTrained bool `json:"is_trained"`
	IndexConfig map[string]interface{} `json:"index_config"`
}

type _IndexInfoResponseModel IndexInfoResponseModel

// NewIndexInfoResponseModel instantiates a new IndexInfoResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexInfoResponseModel(indexName string, indexType string, isTrained bool, indexConfig map[string]interface{}) *IndexInfoResponseModel {
	this := IndexInfoResponseModel{}
	this.IndexName = indexName
	this.IndexType = indexType
	this.IsTrained = isTrained
	this.IndexConfig = indexConfig
	return &this
}

// NewIndexInfoResponseModelWithDefaults instantiates a new IndexInfoResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexInfoResponseModelWithDefaults() *IndexInfoResponseModel {
	this := IndexInfoResponseModel{}
	return &this
}

// GetIndexName returns the IndexName field value
func (o *IndexInfoResponseModel) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *IndexInfoResponseModel) SetIndexName(v string) {
	o.IndexName = v
}

// GetIndexType returns the IndexType field value
func (o *IndexInfoResponseModel) GetIndexType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexType
}

// GetIndexTypeOk returns a tuple with the IndexType field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetIndexTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexType, true
}

// SetIndexType sets field value
func (o *IndexInfoResponseModel) SetIndexType(v string) {
	o.IndexType = v
}

// GetIsTrained returns the IsTrained field value
func (o *IndexInfoResponseModel) GetIsTrained() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsTrained
}

// GetIsTrainedOk returns a tuple with the IsTrained field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetIsTrainedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsTrained, true
}

// SetIsTrained sets field value
func (o *IndexInfoResponseModel) SetIsTrained(v bool) {
	o.IsTrained = v
}

// GetIndexConfig returns the IndexConfig field value
func (o *IndexInfoResponseModel) GetIndexConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.IndexConfig
}

// GetIndexConfigOk returns a tuple with the IndexConfig field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetIndexConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.IndexConfig, true
}

// SetIndexConfig sets field value
func (o *IndexInfoResponseModel) SetIndexConfig(v map[string]interface{}) {
	o.IndexConfig = v
}

func (o IndexInfoResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexInfoResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index_name"] = o.IndexName
	toSerialize["index_type"] = o.IndexType
	toSerialize["is_trained"] = o.IsTrained
	toSerialize["index_config"] = o.IndexConfig
	return toSerialize, nil
}

func (o *IndexInfoResponseModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index_name",
		"index_type",
		"is_trained",
		"index_config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIndexInfoResponseModel := _IndexInfoResponseModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIndexInfoResponseModel)

	if err != nil {
		return err
	}

	*o = IndexInfoResponseModel(varIndexInfoResponseModel)

	return err
}

type NullableIndexInfoResponseModel struct {
	value *IndexInfoResponseModel
	isSet bool
}

func (v NullableIndexInfoResponseModel) Get() *IndexInfoResponseModel {
	return v.value
}

func (v *NullableIndexInfoResponseModel) Set(val *IndexInfoResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexInfoResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexInfoResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexInfoResponseModel(val *IndexInfoResponseModel) *NullableIndexInfoResponseModel {
	return &NullableIndexInfoResponseModel{value: val, isSet: true}
}

func (v NullableIndexInfoResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexInfoResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


