/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
)

// checks if the IndexIVFModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexIVFModel{}

// IndexIVFModel Model for configuring an IVF (Inverted File) index.  Attributes:     type (str): Index type identifier. Defaults to \"ivf\".
type IndexIVFModel struct {
	Dimension NullableInt32 `json:"dimension,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewIndexIVFModel instantiates a new IndexIVFModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexIVFModel() *IndexIVFModel {
	this := IndexIVFModel{}
	var type_ string = "ivf"
	this.Type = &type_
	return &this
}

// NewIndexIVFModelWithDefaults instantiates a new IndexIVFModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexIVFModelWithDefaults() *IndexIVFModel {
	this := IndexIVFModel{}
	var type_ string = "ivf"
	this.Type = &type_
	return &this
}

// GetDimension returns the Dimension field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexIVFModel) GetDimension() int32 {
	if o == nil || IsNil(o.Dimension.Get()) {
		var ret int32
		return ret
	}
	return *o.Dimension.Get()
}

// GetDimensionOk returns a tuple with the Dimension field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexIVFModel) GetDimensionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dimension.Get(), o.Dimension.IsSet()
}

// HasDimension returns a boolean if a field has been set.
func (o *IndexIVFModel) HasDimension() bool {
	if o != nil && o.Dimension.IsSet() {
		return true
	}

	return false
}

// SetDimension gets a reference to the given NullableInt32 and assigns it to the Dimension field.
func (o *IndexIVFModel) SetDimension(v int32) {
	o.Dimension.Set(&v)
}
// SetDimensionNil sets the value for Dimension to be an explicit nil
func (o *IndexIVFModel) SetDimensionNil() {
	o.Dimension.Set(nil)
}

// UnsetDimension ensures that no value is present for Dimension, not even an explicit nil
func (o *IndexIVFModel) UnsetDimension() {
	o.Dimension.Unset()
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IndexIVFModel) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexIVFModel) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IndexIVFModel) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IndexIVFModel) SetType(v string) {
	o.Type = &v
}

func (o IndexIVFModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexIVFModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Dimension.IsSet() {
		toSerialize["dimension"] = o.Dimension.Get()
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableIndexIVFModel struct {
	value *IndexIVFModel
	isSet bool
}

func (v NullableIndexIVFModel) Get() *IndexIVFModel {
	return v.value
}

func (v *NullableIndexIVFModel) Set(val *IndexIVFModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexIVFModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexIVFModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexIVFModel(val *IndexIVFModel) *NullableIndexIVFModel {
	return &NullableIndexIVFModel{value: val, isSet: true}
}

func (v NullableIndexIVFModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexIVFModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


