/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VectorItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VectorItem{}

// VectorItem Represents a vectorized item for storage in the encrypted index.  Attributes:     id (str): Unique identifier for the vector item.     vector (Optional[List[float]]): The vector representation of the item.     contents (Optional[Union[str, bytes]]): The original text or associated content (can be string or bytes).     metadata (Optional[Dict[str, Any]]): Additional metadata associated with the item.
type VectorItem struct {
	Id string `json:"id"`
	Vector []float32 `json:"vector,omitempty"`
	Contents NullableContents `json:"contents,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _VectorItem VectorItem

// NewVectorItem instantiates a new VectorItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVectorItem(id string) *VectorItem {
	this := VectorItem{}
	this.Id = id
	return &this
}

// NewVectorItemWithDefaults instantiates a new VectorItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVectorItemWithDefaults() *VectorItem {
	this := VectorItem{}
	return &this
}

// GetId returns the Id field value
func (o *VectorItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VectorItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VectorItem) SetId(v string) {
	o.Id = v
}

// GetVector returns the Vector field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VectorItem) GetVector() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}
	return o.Vector
}

// GetVectorOk returns a tuple with the Vector field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VectorItem) GetVectorOk() ([]float32, bool) {
	if o == nil || IsNil(o.Vector) {
		return nil, false
	}
	return o.Vector, true
}

// HasVector returns a boolean if a field has been set.
func (o *VectorItem) HasVector() bool {
	if o != nil && !IsNil(o.Vector) {
		return true
	}

	return false
}

// SetVector gets a reference to the given []float32 and assigns it to the Vector field.
func (o *VectorItem) SetVector(v []float32) {
	o.Vector = v
}

// GetContents returns the Contents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VectorItem) GetContents() Contents {
	if o == nil || IsNil(o.Contents.Get()) {
		var ret Contents
		return ret
	}
	return *o.Contents.Get()
}

// GetContentsOk returns a tuple with the Contents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VectorItem) GetContentsOk() (*Contents, bool) {
	if o == nil {
		return nil, false
	}
	return o.Contents.Get(), o.Contents.IsSet()
}

// HasContents returns a boolean if a field has been set.
func (o *VectorItem) HasContents() bool {
	if o != nil && o.Contents.IsSet() {
		return true
	}

	return false
}

// SetContents gets a reference to the given NullableContents and assigns it to the Contents field.
func (o *VectorItem) SetContents(v Contents) {
	o.Contents.Set(&v)
}
// SetContentsNil sets the value for Contents to be an explicit nil
func (o *VectorItem) SetContentsNil() {
	o.Contents.Set(nil)
}

// UnsetContents ensures that no value is present for Contents, not even an explicit nil
func (o *VectorItem) UnsetContents() {
	o.Contents.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VectorItem) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VectorItem) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *VectorItem) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *VectorItem) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o VectorItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VectorItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.Vector != nil {
		toSerialize["vector"] = o.Vector
	}
	if o.Contents.IsSet() {
		toSerialize["contents"] = o.Contents.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *VectorItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVectorItem := _VectorItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVectorItem)

	if err != nil {
		return err
	}

	*o = VectorItem(varVectorItem)

	return err
}

type NullableVectorItem struct {
	value *VectorItem
	isSet bool
}

func (v NullableVectorItem) Get() *VectorItem {
	return v.value
}

func (v *NullableVectorItem) Set(val *VectorItem) {
	v.value = val
	v.isSet = true
}

func (v NullableVectorItem) IsSet() bool {
	return v.isSet
}

func (v *NullableVectorItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVectorItem(val *VectorItem) *NullableVectorItem {
	return &NullableVectorItem{value: val, isSet: true}
}

func (v NullableVectorItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVectorItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


