/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpsertVectorsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertVectorsRequest{}

// UpsertVectorsRequest struct for UpsertVectorsRequest
type UpsertVectorsRequest struct {
	Ids     []string    `json:"ids"`
	Vectors [][]float64 `json:"vectors"`
}

type _UpsertVectorsRequest UpsertVectorsRequest

// NewUpsertVectorsRequest instantiates a new UpsertVectorsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertVectorsRequest(ids []string, vectors [][]float64) *UpsertVectorsRequest {
	this := UpsertVectorsRequest{}
	this.Ids = ids
	this.Vectors = vectors
	return &this
}

// NewUpsertVectorsRequestWithDefaults instantiates a new UpsertVectorsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertVectorsRequestWithDefaults() *UpsertVectorsRequest {
	this := UpsertVectorsRequest{}
	return &this
}

// GetIds returns the Ids field value
func (o *UpsertVectorsRequest) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *UpsertVectorsRequest) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *UpsertVectorsRequest) SetIds(v []string) {
	o.Ids = v
}

// GetVectors returns the Vectors field value
func (o *UpsertVectorsRequest) GetVectors() [][]float64 {
	if o == nil {
		var ret [][]float64
		return ret
	}

	return o.Vectors
}

// GetVectorsOk returns a tuple with the Vectors field value
// and a boolean to check if the value has been set.
func (o *UpsertVectorsRequest) GetVectorsOk() ([][]float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vectors, true
}

// SetVectors sets field value
func (o *UpsertVectorsRequest) SetVectors(v [][]float64) {
	o.Vectors = v
}

func (o UpsertVectorsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertVectorsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ids"] = o.Ids
	toSerialize["vectors"] = o.Vectors
	return toSerialize, nil
}

func (o *UpsertVectorsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ids",
		"vectors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpsertVectorsRequest := _UpsertVectorsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpsertVectorsRequest)

	if err != nil {
		return err
	}

	*o = UpsertVectorsRequest(varUpsertVectorsRequest)

	return err
}

type NullableUpsertVectorsRequest struct {
	value *UpsertVectorsRequest
	isSet bool
}

func (v NullableUpsertVectorsRequest) Get() *UpsertVectorsRequest {
	return v.value
}

func (v *NullableUpsertVectorsRequest) Set(val *UpsertVectorsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertVectorsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertVectorsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertVectorsRequest(val *UpsertVectorsRequest) *NullableUpsertVectorsRequest {
	return &NullableUpsertVectorsRequest{value: val, isSet: true}
}

func (v NullableUpsertVectorsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertVectorsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
