/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.16.3.dev86
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
)

// checks if the IndexInfoResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexInfoResponseModel{}

// IndexInfoResponseModel Response model for retrieving information about an index.  Attributes:     index_name (str): The name of the index.     is_trained (bool): Indicates whether the index has been trained.     dimension (int): Dimensionality of the vectors. `0` before the         first upsert when create_index was called without an explicit         dimension (auto-detect).     metric (str): Distance metric (`euclidean`, `cosine`, or         `squared_euclidean`).     n_lists (int): Number of inverted lists in the IVF index. `1`         for untrained indexes.
type IndexInfoResponseModel struct {
	Dimension int32 `json:"dimension"`
	IndexName string `json:"index_name"`
	IsTrained bool `json:"is_trained"`
	Metric string `json:"metric"`
	NLists int32 `json:"n_lists"`
}

type _IndexInfoResponseModel IndexInfoResponseModel

// NewIndexInfoResponseModel instantiates a new IndexInfoResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexInfoResponseModel(dimension int32, indexName string, isTrained bool, metric string, nLists int32) *IndexInfoResponseModel {
	this := IndexInfoResponseModel{}
	this.Dimension = dimension
	this.IndexName = indexName
	this.IsTrained = isTrained
	this.Metric = metric
	this.NLists = nLists
	return &this
}

// NewIndexInfoResponseModelWithDefaults instantiates a new IndexInfoResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexInfoResponseModelWithDefaults() *IndexInfoResponseModel {
	this := IndexInfoResponseModel{}
	return &this
}

// GetDimension returns the Dimension field value
func (o *IndexInfoResponseModel) GetDimension() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Dimension
}

// GetDimensionOk returns a tuple with the Dimension field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetDimensionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dimension, true
}

// SetDimension sets field value
func (o *IndexInfoResponseModel) SetDimension(v int32) {
	o.Dimension = v
}

// GetIndexName returns the IndexName field value
func (o *IndexInfoResponseModel) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *IndexInfoResponseModel) SetIndexName(v string) {
	o.IndexName = v
}

// GetIsTrained returns the IsTrained field value
func (o *IndexInfoResponseModel) GetIsTrained() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsTrained
}

// GetIsTrainedOk returns a tuple with the IsTrained field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetIsTrainedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsTrained, true
}

// SetIsTrained sets field value
func (o *IndexInfoResponseModel) SetIsTrained(v bool) {
	o.IsTrained = v
}

// GetMetric returns the Metric field value
func (o *IndexInfoResponseModel) GetMetric() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetMetricOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *IndexInfoResponseModel) SetMetric(v string) {
	o.Metric = v
}

// GetNLists returns the NLists field value
func (o *IndexInfoResponseModel) GetNLists() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NLists
}

// GetNListsOk returns a tuple with the NLists field value
// and a boolean to check if the value has been set.
func (o *IndexInfoResponseModel) GetNListsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NLists, true
}

// SetNLists sets field value
func (o *IndexInfoResponseModel) SetNLists(v int32) {
	o.NLists = v
}

func (o IndexInfoResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexInfoResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dimension"] = o.Dimension
	toSerialize["index_name"] = o.IndexName
	toSerialize["is_trained"] = o.IsTrained
	toSerialize["metric"] = o.Metric
	toSerialize["n_lists"] = o.NLists
	return toSerialize, nil
}

func (o *IndexInfoResponseModel) UnmarshalJSON(data []byte) (err error) {
	// Accept both the flat shape and the legacy nested
	// `index_config: {dimension, metric, n_lists}` shape the service
	// still returns on /v1/indexes/describe.
	var raw struct {
		Dimension   *int32  `json:"dimension"`
		IndexName   string  `json:"index_name"`
		IsTrained   bool    `json:"is_trained"`
		Metric      *string `json:"metric"`
		NLists      *int32  `json:"n_lists"`
		IndexConfig *struct {
			Dimension *int32  `json:"dimension"`
			Metric    *string `json:"metric"`
			NLists    *int32  `json:"n_lists"`
		} `json:"index_config"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	o.IndexName = raw.IndexName
	o.IsTrained = raw.IsTrained

	var ncDim, ncNLists *int32
	var ncMetric *string
	if raw.IndexConfig != nil {
		ncDim = raw.IndexConfig.Dimension
		ncMetric = raw.IndexConfig.Metric
		ncNLists = raw.IndexConfig.NLists
	}

	switch {
	case raw.Dimension != nil:
		o.Dimension = *raw.Dimension
	case ncDim != nil:
		o.Dimension = *ncDim
	}
	switch {
	case raw.Metric != nil:
		o.Metric = *raw.Metric
	case ncMetric != nil:
		o.Metric = *ncMetric
	}
	switch {
	case raw.NLists != nil:
		o.NLists = *raw.NLists
	case ncNLists != nil:
		o.NLists = *ncNLists
	}

	return nil
}

type NullableIndexInfoResponseModel struct {
	value *IndexInfoResponseModel
	isSet bool
}

func (v NullableIndexInfoResponseModel) Get() *IndexInfoResponseModel {
	return v.value
}

func (v *NullableIndexInfoResponseModel) Set(val *IndexInfoResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexInfoResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexInfoResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexInfoResponseModel(val *IndexInfoResponseModel) *NullableIndexInfoResponseModel {
	return &NullableIndexInfoResponseModel{value: val, isSet: true}
}

func (v NullableIndexInfoResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexInfoResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


