/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VectorItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VectorItem{}

// VectorItem struct for VectorItem
type VectorItem struct {
	Id       string                 `json:"id"`
	Vector   []float32              `json:"vector,omitempty"`
	Contents *string                `json:"contents,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _VectorItem VectorItem

// NewVectorItem instantiates a new VectorItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVectorItem(id string) *VectorItem {
	this := VectorItem{}
	this.Id = id
	return &this
}

// NewVectorItemWithDefaults instantiates a new VectorItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVectorItemWithDefaults() *VectorItem {
	this := VectorItem{}
	return &this
}

// GetId returns the Id field value
func (o *VectorItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VectorItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VectorItem) SetId(v string) {
	o.Id = v
}

// GetVector returns the Vector field value if set, zero value otherwise.
func (o *VectorItem) GetVector() []float32 {
	if o == nil || IsNil(o.Vector) {
		var ret []float32
		return ret
	}
	return o.Vector
}

// GetVectorOk returns a tuple with the Vector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorItem) GetVectorOk() ([]float32, bool) {
	if o == nil || IsNil(o.Vector) {
		return nil, false
	}
	return o.Vector, true
}

// HasVector returns a boolean if a field has been set.
func (o *VectorItem) HasVector() bool {
	if o != nil && !IsNil(o.Vector) {
		return true
	}

	return false
}

// SetVector gets a reference to the given []float32 and assigns it to the Vector field.
func (o *VectorItem) SetVector(v []float32) {
	o.Vector = v
}

// GetContents returns the Contents field value if set, zero value otherwise.
func (o *VectorItem) GetContents() string {
	if o == nil || IsNil(o.Contents) {
		var ret string
		return ret
	}
	return *o.Contents
}

// GetContentsOk returns a tuple with the Contents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorItem) GetContentsOk() (*string, bool) {
	if o == nil || IsNil(o.Contents) {
		return nil, false
	}
	return o.Contents, true
}

// HasContents returns a boolean if a field has been set.
func (o *VectorItem) HasContents() bool {
	if o != nil && !IsNil(o.Contents) {
		return true
	}

	return false
}

// SetContents gets a reference to the given string and assigns it to the Contents field.
func (o *VectorItem) SetContents(v string) {
	o.Contents = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *VectorItem) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorItem) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *VectorItem) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *VectorItem) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o VectorItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VectorItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Vector) {
		toSerialize["vector"] = o.Vector
	}
	if !IsNil(o.Contents) {
		toSerialize["contents"] = o.Contents
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *VectorItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVectorItem := _VectorItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVectorItem)

	if err != nil {
		return err
	}

	*o = VectorItem(varVectorItem)

	return err
}

type NullableVectorItem struct {
	value *VectorItem
	isSet bool
}

func (v NullableVectorItem) Get() *VectorItem {
	return v.value
}

func (v *NullableVectorItem) Set(val *VectorItem) {
	v.value = val
	v.isSet = true
}

func (v NullableVectorItem) IsSet() bool {
	return v.isSet
}

func (v *NullableVectorItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVectorItem(val *VectorItem) *NullableVectorItem {
	return &NullableVectorItem{value: val, isSet: true}
}

func (v NullableVectorItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVectorItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
