/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.17.1.dev16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"fmt"
)


// OrderBy Metadata field to sort matches by, applied after filtering. Accepts a field name, or a single-field MongoDB-style dict such as {'views': -1} (1 ascending, -1 descending) which overrides `ascending`. Unordered when omitted. Items missing the field, or holding a non-scalar, sort last. Not supported with `text`.
type OrderBy struct {
	MapmapOfStringint32 *map[string]int32
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *OrderBy) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into MapmapOfStringint32
	err = json.Unmarshal(data, &dst.MapmapOfStringint32);
	if err == nil {
		jsonMapmapOfStringint32, _ := json.Marshal(dst.MapmapOfStringint32)
		if string(jsonMapmapOfStringint32) == "{}" { // empty struct
			dst.MapmapOfStringint32 = nil
		} else {
			return nil // data stored in dst.MapmapOfStringint32, return on the first match
		}
	} else {
		dst.MapmapOfStringint32 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(OrderBy)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OrderBy) MarshalJSON() ([]byte, error) {
	if src.MapmapOfStringint32 != nil {
		return json.Marshal(&src.MapmapOfStringint32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableOrderBy struct {
	value *OrderBy
	isSet bool
}

func (v NullableOrderBy) Get() *OrderBy {
	return v.value
}

func (v *NullableOrderBy) Set(val *OrderBy) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderBy) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderBy(val *OrderBy) *NullableOrderBy {
	return &NullableOrderBy{value: val, isSet: true}
}

func (v NullableOrderBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


