/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.17.1.dev16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryRequest{}

// QueryRequest Request model for performing a similarity search in the encrypted index.  Inherits:     IndexOperationRequest: Includes `index_name` and `index_key`.     HybridQueryParams: `text` and the fusion knobs that turn this into a         hybrid (BM25 + vector) query. A query vector is still required         even when `text` is set.  Attributes:     query_vectors (Optional[List[float]]): The vector used for the similarity search.     query_contents (Optional[str]): Text-based content used for semantic search.     top_k (Optional[int]): Number of nearest neighbors to return for each query. Defaults to 100.     n_probes (Optional[int]): Number of lists to probe during the query. Defaults to auto.     greedy (Optional[bool]): Whether to use greedy search. Defaults to False.     rerank_mult (Optional[int]): Multiplier for stage 1 retrieval in reranking indexes. Defaults to 10.     filters (Optional[Dict[str, Any]]): Metadata filters as a JSON-like         dictionary (see `FILTERS_DESCRIPTION` for the operator set).         Defaults to {}.     include (List[str]): List of additional fields to include in the response. Defaults to `[]` (only IDs are returned).
type QueryRequest struct {
	// Query text for a BM25 full-text leg. Requires an index with at least one full_text field. Omitted/empty leaves the query text-free.
	Text NullableString `json:"text,omitempty"`
	// full_text fields the text leg searches; omitted means all of them. Naming a non-full_text field raises.
	TextFields []string `json:"text_fields,omitempty"`
	// Per-field weights on the summed per-field BM25 scores, parallel to the searched fields. Omitted means 1.0 each.
	TextFieldWeights []float32 `json:"text_field_weights,omitempty"`
	// Require every query term to match (AND) instead of any (OR, the default).
	RequireAllTerms NullableBool `json:"require_all_terms,omitempty"`
	// Leg blend in [0, 1]: 0 = pure BM25, 1 = pure vector; omitted means 0.5. An exact endpoint skips the dead leg's retrieval.
	Alpha NullableFloat32 `json:"alpha,omitempty"`
	// RRF rank-smoothing constant (> 0; omitted means 60). Higher rewards agreement further down each leg's list.
	RrfK NullableFloat32 `json:"rrf_k,omitempty"`
	// Per-leg candidate depth as a multiple of top_k (>= 1; omitted means 3), so each leg looks deeper than the final cut.
	WindowMult NullableInt32 `json:"window_mult,omitempty"`
	// ID name
	IndexName string `json:"index_name"`
	// 32-byte encryption key as hex string.  Required for SDK-supplied indexes; must be omitted for KMS-backed indexes (the service resolves the KEK via the index's KMSBlob).
	IndexKey NullableString `json:"index_key,omitempty"`
	QueryVectors []float32 `json:"query_vectors,omitempty"`
	QueryContents NullableString `json:"query_contents,omitempty"`
	TopK NullableInt32 `json:"top_k,omitempty"`
	NProbes NullableInt32 `json:"n_probes,omitempty"`
	RerankMult NullableInt32 `json:"rerank_mult,omitempty"`
	Greedy NullableBool `json:"greedy,omitempty"`
	// Metadata filters as a JSON object. Operators: `$eq`, `$ne`, `$in`, `$nin`, `$exists`, `$gt`, `$gte`, `$lt`, `$lte`, `$regex`, `$contains`, combined with `$and` / `$or` / `$nor` / `$not`. Filtering works on any metadata field; the index's `metadata_schema` only decides how a filter is resolved — fields marked `filterable` (the default) are answered from the inverted index, and `$regex` / `$contains` are answered from the regex dictionary on `pattern` fields. Anything else falls back to a post-filter over the decrypted metadata, which is correct but slower. Dates have no native type: store and filter them as epoch milliseconds.
	Filters map[string]interface{} `json:"filters,omitempty"`
	Include []string `json:"include,omitempty"`
}

type _QueryRequest QueryRequest

// NewQueryRequest instantiates a new QueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryRequest(indexName string) *QueryRequest {
	this := QueryRequest{}
	this.IndexName = indexName
	return &this
}

// NewQueryRequestWithDefaults instantiates a new QueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryRequestWithDefaults() *QueryRequest {
	this := QueryRequest{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetText() string {
	if o == nil || IsNil(o.Text.Get()) {
		var ret string
		return ret
	}
	return *o.Text.Get()
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Text.Get(), o.Text.IsSet()
}

// HasText returns a boolean if a field has been set.
func (o *QueryRequest) HasText() bool {
	if o != nil && o.Text.IsSet() {
		return true
	}

	return false
}

// SetText gets a reference to the given NullableString and assigns it to the Text field.
func (o *QueryRequest) SetText(v string) {
	o.Text.Set(&v)
}
// SetTextNil sets the value for Text to be an explicit nil
func (o *QueryRequest) SetTextNil() {
	o.Text.Set(nil)
}

// UnsetText ensures that no value is present for Text, not even an explicit nil
func (o *QueryRequest) UnsetText() {
	o.Text.Unset()
}

// GetTextFields returns the TextFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetTextFields() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.TextFields
}

// GetTextFieldsOk returns a tuple with the TextFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetTextFieldsOk() ([]string, bool) {
	if o == nil || IsNil(o.TextFields) {
		return nil, false
	}
	return o.TextFields, true
}

// HasTextFields returns a boolean if a field has been set.
func (o *QueryRequest) HasTextFields() bool {
	if o != nil && !IsNil(o.TextFields) {
		return true
	}

	return false
}

// SetTextFields gets a reference to the given []string and assigns it to the TextFields field.
func (o *QueryRequest) SetTextFields(v []string) {
	o.TextFields = v
}

// GetTextFieldWeights returns the TextFieldWeights field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetTextFieldWeights() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}
	return o.TextFieldWeights
}

// GetTextFieldWeightsOk returns a tuple with the TextFieldWeights field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetTextFieldWeightsOk() ([]float32, bool) {
	if o == nil || IsNil(o.TextFieldWeights) {
		return nil, false
	}
	return o.TextFieldWeights, true
}

// HasTextFieldWeights returns a boolean if a field has been set.
func (o *QueryRequest) HasTextFieldWeights() bool {
	if o != nil && !IsNil(o.TextFieldWeights) {
		return true
	}

	return false
}

// SetTextFieldWeights gets a reference to the given []float32 and assigns it to the TextFieldWeights field.
func (o *QueryRequest) SetTextFieldWeights(v []float32) {
	o.TextFieldWeights = v
}

// GetRequireAllTerms returns the RequireAllTerms field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetRequireAllTerms() bool {
	if o == nil || IsNil(o.RequireAllTerms.Get()) {
		var ret bool
		return ret
	}
	return *o.RequireAllTerms.Get()
}

// GetRequireAllTermsOk returns a tuple with the RequireAllTerms field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetRequireAllTermsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequireAllTerms.Get(), o.RequireAllTerms.IsSet()
}

// HasRequireAllTerms returns a boolean if a field has been set.
func (o *QueryRequest) HasRequireAllTerms() bool {
	if o != nil && o.RequireAllTerms.IsSet() {
		return true
	}

	return false
}

// SetRequireAllTerms gets a reference to the given NullableBool and assigns it to the RequireAllTerms field.
func (o *QueryRequest) SetRequireAllTerms(v bool) {
	o.RequireAllTerms.Set(&v)
}
// SetRequireAllTermsNil sets the value for RequireAllTerms to be an explicit nil
func (o *QueryRequest) SetRequireAllTermsNil() {
	o.RequireAllTerms.Set(nil)
}

// UnsetRequireAllTerms ensures that no value is present for RequireAllTerms, not even an explicit nil
func (o *QueryRequest) UnsetRequireAllTerms() {
	o.RequireAllTerms.Unset()
}

// GetAlpha returns the Alpha field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetAlpha() float32 {
	if o == nil || IsNil(o.Alpha.Get()) {
		var ret float32
		return ret
	}
	return *o.Alpha.Get()
}

// GetAlphaOk returns a tuple with the Alpha field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetAlphaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Alpha.Get(), o.Alpha.IsSet()
}

// HasAlpha returns a boolean if a field has been set.
func (o *QueryRequest) HasAlpha() bool {
	if o != nil && o.Alpha.IsSet() {
		return true
	}

	return false
}

// SetAlpha gets a reference to the given NullableFloat32 and assigns it to the Alpha field.
func (o *QueryRequest) SetAlpha(v float32) {
	o.Alpha.Set(&v)
}
// SetAlphaNil sets the value for Alpha to be an explicit nil
func (o *QueryRequest) SetAlphaNil() {
	o.Alpha.Set(nil)
}

// UnsetAlpha ensures that no value is present for Alpha, not even an explicit nil
func (o *QueryRequest) UnsetAlpha() {
	o.Alpha.Unset()
}

// GetRrfK returns the RrfK field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetRrfK() float32 {
	if o == nil || IsNil(o.RrfK.Get()) {
		var ret float32
		return ret
	}
	return *o.RrfK.Get()
}

// GetRrfKOk returns a tuple with the RrfK field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetRrfKOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RrfK.Get(), o.RrfK.IsSet()
}

// HasRrfK returns a boolean if a field has been set.
func (o *QueryRequest) HasRrfK() bool {
	if o != nil && o.RrfK.IsSet() {
		return true
	}

	return false
}

// SetRrfK gets a reference to the given NullableFloat32 and assigns it to the RrfK field.
func (o *QueryRequest) SetRrfK(v float32) {
	o.RrfK.Set(&v)
}
// SetRrfKNil sets the value for RrfK to be an explicit nil
func (o *QueryRequest) SetRrfKNil() {
	o.RrfK.Set(nil)
}

// UnsetRrfK ensures that no value is present for RrfK, not even an explicit nil
func (o *QueryRequest) UnsetRrfK() {
	o.RrfK.Unset()
}

// GetWindowMult returns the WindowMult field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetWindowMult() int32 {
	if o == nil || IsNil(o.WindowMult.Get()) {
		var ret int32
		return ret
	}
	return *o.WindowMult.Get()
}

// GetWindowMultOk returns a tuple with the WindowMult field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetWindowMultOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WindowMult.Get(), o.WindowMult.IsSet()
}

// HasWindowMult returns a boolean if a field has been set.
func (o *QueryRequest) HasWindowMult() bool {
	if o != nil && o.WindowMult.IsSet() {
		return true
	}

	return false
}

// SetWindowMult gets a reference to the given NullableInt32 and assigns it to the WindowMult field.
func (o *QueryRequest) SetWindowMult(v int32) {
	o.WindowMult.Set(&v)
}
// SetWindowMultNil sets the value for WindowMult to be an explicit nil
func (o *QueryRequest) SetWindowMultNil() {
	o.WindowMult.Set(nil)
}

// UnsetWindowMult ensures that no value is present for WindowMult, not even an explicit nil
func (o *QueryRequest) UnsetWindowMult() {
	o.WindowMult.Unset()
}

// GetIndexName returns the IndexName field value
func (o *QueryRequest) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *QueryRequest) SetIndexName(v string) {
	o.IndexName = v
}

// GetIndexKey returns the IndexKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetIndexKey() string {
	if o == nil || IsNil(o.IndexKey.Get()) {
		var ret string
		return ret
	}
	return *o.IndexKey.Get()
}

// GetIndexKeyOk returns a tuple with the IndexKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetIndexKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IndexKey.Get(), o.IndexKey.IsSet()
}

// HasIndexKey returns a boolean if a field has been set.
func (o *QueryRequest) HasIndexKey() bool {
	if o != nil && o.IndexKey.IsSet() {
		return true
	}

	return false
}

// SetIndexKey gets a reference to the given NullableString and assigns it to the IndexKey field.
func (o *QueryRequest) SetIndexKey(v string) {
	o.IndexKey.Set(&v)
}
// SetIndexKeyNil sets the value for IndexKey to be an explicit nil
func (o *QueryRequest) SetIndexKeyNil() {
	o.IndexKey.Set(nil)
}

// UnsetIndexKey ensures that no value is present for IndexKey, not even an explicit nil
func (o *QueryRequest) UnsetIndexKey() {
	o.IndexKey.Unset()
}

// GetQueryVectors returns the QueryVectors field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetQueryVectors() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}
	return o.QueryVectors
}

// GetQueryVectorsOk returns a tuple with the QueryVectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetQueryVectorsOk() ([]float32, bool) {
	if o == nil || IsNil(o.QueryVectors) {
		return nil, false
	}
	return o.QueryVectors, true
}

// HasQueryVectors returns a boolean if a field has been set.
func (o *QueryRequest) HasQueryVectors() bool {
	if o != nil && !IsNil(o.QueryVectors) {
		return true
	}

	return false
}

// SetQueryVectors gets a reference to the given []float32 and assigns it to the QueryVectors field.
func (o *QueryRequest) SetQueryVectors(v []float32) {
	o.QueryVectors = v
}

// GetQueryContents returns the QueryContents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetQueryContents() string {
	if o == nil || IsNil(o.QueryContents.Get()) {
		var ret string
		return ret
	}
	return *o.QueryContents.Get()
}

// GetQueryContentsOk returns a tuple with the QueryContents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetQueryContentsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueryContents.Get(), o.QueryContents.IsSet()
}

// HasQueryContents returns a boolean if a field has been set.
func (o *QueryRequest) HasQueryContents() bool {
	if o != nil && o.QueryContents.IsSet() {
		return true
	}

	return false
}

// SetQueryContents gets a reference to the given NullableString and assigns it to the QueryContents field.
func (o *QueryRequest) SetQueryContents(v string) {
	o.QueryContents.Set(&v)
}
// SetQueryContentsNil sets the value for QueryContents to be an explicit nil
func (o *QueryRequest) SetQueryContentsNil() {
	o.QueryContents.Set(nil)
}

// UnsetQueryContents ensures that no value is present for QueryContents, not even an explicit nil
func (o *QueryRequest) UnsetQueryContents() {
	o.QueryContents.Unset()
}

// GetTopK returns the TopK field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetTopK() int32 {
	if o == nil || IsNil(o.TopK.Get()) {
		var ret int32
		return ret
	}
	return *o.TopK.Get()
}

// GetTopKOk returns a tuple with the TopK field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetTopKOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopK.Get(), o.TopK.IsSet()
}

// HasTopK returns a boolean if a field has been set.
func (o *QueryRequest) HasTopK() bool {
	if o != nil && o.TopK.IsSet() {
		return true
	}

	return false
}

// SetTopK gets a reference to the given NullableInt32 and assigns it to the TopK field.
func (o *QueryRequest) SetTopK(v int32) {
	o.TopK.Set(&v)
}
// SetTopKNil sets the value for TopK to be an explicit nil
func (o *QueryRequest) SetTopKNil() {
	o.TopK.Set(nil)
}

// UnsetTopK ensures that no value is present for TopK, not even an explicit nil
func (o *QueryRequest) UnsetTopK() {
	o.TopK.Unset()
}

// GetNProbes returns the NProbes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetNProbes() int32 {
	if o == nil || IsNil(o.NProbes.Get()) {
		var ret int32
		return ret
	}
	return *o.NProbes.Get()
}

// GetNProbesOk returns a tuple with the NProbes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetNProbesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NProbes.Get(), o.NProbes.IsSet()
}

// HasNProbes returns a boolean if a field has been set.
func (o *QueryRequest) HasNProbes() bool {
	if o != nil && o.NProbes.IsSet() {
		return true
	}

	return false
}

// SetNProbes gets a reference to the given NullableInt32 and assigns it to the NProbes field.
func (o *QueryRequest) SetNProbes(v int32) {
	o.NProbes.Set(&v)
}
// SetNProbesNil sets the value for NProbes to be an explicit nil
func (o *QueryRequest) SetNProbesNil() {
	o.NProbes.Set(nil)
}

// UnsetNProbes ensures that no value is present for NProbes, not even an explicit nil
func (o *QueryRequest) UnsetNProbes() {
	o.NProbes.Unset()
}

// GetRerankMult returns the RerankMult field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetRerankMult() int32 {
	if o == nil || IsNil(o.RerankMult.Get()) {
		var ret int32
		return ret
	}
	return *o.RerankMult.Get()
}

// GetRerankMultOk returns a tuple with the RerankMult field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetRerankMultOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RerankMult.Get(), o.RerankMult.IsSet()
}

// HasRerankMult returns a boolean if a field has been set.
func (o *QueryRequest) HasRerankMult() bool {
	if o != nil && o.RerankMult.IsSet() {
		return true
	}

	return false
}

// SetRerankMult gets a reference to the given NullableInt32 and assigns it to the RerankMult field.
func (o *QueryRequest) SetRerankMult(v int32) {
	o.RerankMult.Set(&v)
}
// SetRerankMultNil sets the value for RerankMult to be an explicit nil
func (o *QueryRequest) SetRerankMultNil() {
	o.RerankMult.Set(nil)
}

// UnsetRerankMult ensures that no value is present for RerankMult, not even an explicit nil
func (o *QueryRequest) UnsetRerankMult() {
	o.RerankMult.Unset()
}

// GetGreedy returns the Greedy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetGreedy() bool {
	if o == nil || IsNil(o.Greedy.Get()) {
		var ret bool
		return ret
	}
	return *o.Greedy.Get()
}

// GetGreedyOk returns a tuple with the Greedy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetGreedyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Greedy.Get(), o.Greedy.IsSet()
}

// HasGreedy returns a boolean if a field has been set.
func (o *QueryRequest) HasGreedy() bool {
	if o != nil && o.Greedy.IsSet() {
		return true
	}

	return false
}

// SetGreedy gets a reference to the given NullableBool and assigns it to the Greedy field.
func (o *QueryRequest) SetGreedy(v bool) {
	o.Greedy.Set(&v)
}
// SetGreedyNil sets the value for Greedy to be an explicit nil
func (o *QueryRequest) SetGreedyNil() {
	o.Greedy.Set(nil)
}

// UnsetGreedy ensures that no value is present for Greedy, not even an explicit nil
func (o *QueryRequest) UnsetGreedy() {
	o.Greedy.Unset()
}

// GetFilters returns the Filters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetFilters() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetFiltersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filters) {
		return map[string]interface{}{}, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *QueryRequest) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given map[string]interface{} and assigns it to the Filters field.
func (o *QueryRequest) SetFilters(v map[string]interface{}) {
	o.Filters = v
}

// GetInclude returns the Include field value if set, zero value otherwise.
func (o *QueryRequest) GetInclude() []string {
	if o == nil || IsNil(o.Include) {
		var ret []string
		return ret
	}
	return o.Include
}

// GetIncludeOk returns a tuple with the Include field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetIncludeOk() ([]string, bool) {
	if o == nil || IsNil(o.Include) {
		return nil, false
	}
	return o.Include, true
}

// HasInclude returns a boolean if a field has been set.
func (o *QueryRequest) HasInclude() bool {
	if o != nil && !IsNil(o.Include) {
		return true
	}

	return false
}

// SetInclude gets a reference to the given []string and assigns it to the Include field.
func (o *QueryRequest) SetInclude(v []string) {
	o.Include = v
}

func (o QueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Text.IsSet() {
		toSerialize["text"] = o.Text.Get()
	}
	if o.TextFields != nil {
		toSerialize["text_fields"] = o.TextFields
	}
	if o.TextFieldWeights != nil {
		toSerialize["text_field_weights"] = o.TextFieldWeights
	}
	if o.RequireAllTerms.IsSet() {
		toSerialize["require_all_terms"] = o.RequireAllTerms.Get()
	}
	if o.Alpha.IsSet() {
		toSerialize["alpha"] = o.Alpha.Get()
	}
	if o.RrfK.IsSet() {
		toSerialize["rrf_k"] = o.RrfK.Get()
	}
	if o.WindowMult.IsSet() {
		toSerialize["window_mult"] = o.WindowMult.Get()
	}
	toSerialize["index_name"] = o.IndexName
	if o.IndexKey.IsSet() {
		toSerialize["index_key"] = o.IndexKey.Get()
	}
	if o.QueryVectors != nil {
		toSerialize["query_vectors"] = o.QueryVectors
	}
	if o.QueryContents.IsSet() {
		toSerialize["query_contents"] = o.QueryContents.Get()
	}
	if o.TopK.IsSet() {
		toSerialize["top_k"] = o.TopK.Get()
	}
	if o.NProbes.IsSet() {
		toSerialize["n_probes"] = o.NProbes.Get()
	}
	if o.RerankMult.IsSet() {
		toSerialize["rerank_mult"] = o.RerankMult.Get()
	}
	if o.Greedy.IsSet() {
		toSerialize["greedy"] = o.Greedy.Get()
	}
	if o.Filters != nil {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.Include) {
		toSerialize["include"] = o.Include
	}
	return toSerialize, nil
}

func (o *QueryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryRequest := _QueryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	
	err = decoder.Decode(&varQueryRequest)

	if err != nil {
		return err
	}

	*o = QueryRequest(varQueryRequest)

	return err
}

type NullableQueryRequest struct {
	value *QueryRequest
	isSet bool
}

func (v NullableQueryRequest) Get() *QueryRequest {
	return v.value
}

func (v *NullableQueryRequest) Set(val *QueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryRequest(val *QueryRequest) *NullableQueryRequest {
	return &NullableQueryRequest{value: val, isSet: true}
}

func (v NullableQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


