// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryRequest{}

// QueryRequest struct for QueryRequest
type QueryRequest struct {
	IndexName          string                 `json:"index_name"`
	IndexKey           string                 `json:"index_key"`
	QueryVector        []float32              `json:"query_vector,omitempty"`
	BatchQueryVectors  [][]float32            `json:"query_vectors,omitempty"` // renamed field; JSON key unchanged for compatibility
	QueryContents      *string                `json:"query_contents,omitempty"`
	TopK               int32                  `json:"top_k"`
	NProbes            *int32                 `json:"n_probes,omitempty"` // optional
	Greedy             *bool                  `json:"greedy,omitempty"`
	Filters            map[string]interface{} `json:"filters,omitempty"`
	Include            []string               `json:"include"`
}

type _QueryRequest QueryRequest

// NewQueryRequest instantiates a new QueryRequest object with required fields.
// n_probes is optional; use SetNProbes if you want to set it.
func NewQueryRequest(indexName string, indexKey string, topK int32, include []string) *QueryRequest {
	this := QueryRequest{}
	this.IndexName = indexName
	this.IndexKey = indexKey
	this.TopK = topK
	this.Include = include
	return &this
}

// NewQueryRequestWithDefaults instantiates a new QueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryRequestWithDefaults() *QueryRequest {
	this := QueryRequest{}
	return &this
}

// IndexName
func (o *QueryRequest) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.IndexName
}

func (o *QueryRequest) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

func (o *QueryRequest) SetIndexName(v string) {
	o.IndexName = v
}

// IndexKey
func (o *QueryRequest) GetIndexKey() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.IndexKey
}

func (o *QueryRequest) GetIndexKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexKey, true
}

func (o *QueryRequest) SetIndexKey(v string) {
	o.IndexKey = v
}

// QueryVector
func (o *QueryRequest) GetQueryVector() []float32 {
	if o == nil || IsNil(o.QueryVector) {
		var ret []float32
		return ret
	}
	return o.QueryVector
}

func (o *QueryRequest) GetQueryVectorOk() ([]float32, bool) {
	if o == nil || IsNil(o.QueryVector) {
		return nil, false
	}
	return o.QueryVector, true
}

func (o *QueryRequest) HasQueryVector() bool {
	return o != nil && !IsNil(o.QueryVector)
}

func (o *QueryRequest) SetQueryVector(v []float32) {
	o.QueryVector = v
}

// BatchQueryVectors (renamed from QueryVectors)
func (o *QueryRequest) GetBatchQueryVectors() [][]float32 {
	if o == nil || IsNil(o.BatchQueryVectors) {
		var ret [][]float32
		return ret
	}
	return o.BatchQueryVectors
}

func (o *QueryRequest) GetBatchQueryVectorsOk() ([][]float32, bool) {
	if o == nil || IsNil(o.BatchQueryVectors) {
		return nil, false
	}
	return o.BatchQueryVectors, true
}

func (o *QueryRequest) HasBatchQueryVectors() bool {
	return o != nil && !IsNil(o.BatchQueryVectors)
}

func (o *QueryRequest) SetBatchQueryVectors(v [][]float32) {
	o.BatchQueryVectors = v
}

// QueryContents
func (o *QueryRequest) GetQueryContents() string {
	if o == nil || IsNil(o.QueryContents) {
		var ret string
		return ret
	}
	return *o.QueryContents
}

func (o *QueryRequest) GetQueryContentsOk() (*string, bool) {
	if o == nil || IsNil(o.QueryContents) {
		return nil, false
	}
	return o.QueryContents, true
}

func (o *QueryRequest) HasQueryContents() bool {
	return o != nil && !IsNil(o.QueryContents)
}

func (o *QueryRequest) SetQueryContents(v string) {
	o.QueryContents = &v
}

// TopK
func (o *QueryRequest) GetTopK() int32 {
	if o == nil {
		var ret int32
		return ret
	}
	return o.TopK
}

func (o *QueryRequest) GetTopKOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopK, true
}

func (o *QueryRequest) SetTopK(v int32) {
	o.TopK = v
}

// NProbes (optional)
func (o *QueryRequest) GetNProbes() int32 {
	if o == nil || IsNil(o.NProbes) {
		var ret int32
		return ret
	}
	return *o.NProbes
}

func (o *QueryRequest) GetNProbesOk() (*int32, bool) {
	if o == nil || IsNil(o.NProbes) {
		return nil, false
	}
	return o.NProbes, true
}

func (o *QueryRequest) HasNProbes() bool {
	return o != nil && !IsNil(o.NProbes)
}

func (o *QueryRequest) SetNProbes(v int32) {
	o.NProbes = &v
}

// Greedy (optional)
func (o *QueryRequest) GetGreedy() bool {
	if o == nil || IsNil(o.Greedy) {
		var ret bool
		return ret
	}
	return *o.Greedy
}

func (o *QueryRequest) GetGreedyOk() (*bool, bool) {
	if o == nil || IsNil(o.Greedy) {
		return nil, false
	}
	return o.Greedy, true
}

func (o *QueryRequest) HasGreedy() bool {
	return o != nil && !IsNil(o.Greedy)
}

func (o *QueryRequest) SetGreedy(v bool) {
	o.Greedy = &v
}

// Filters (optional)
func (o *QueryRequest) GetFilters() map[string]interface{} {
	if o == nil || IsNil(o.Filters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Filters
}

func (o *QueryRequest) GetFiltersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filters) {
		return map[string]interface{}{}, false
	}
	return o.Filters, true
}

func (o *QueryRequest) HasFilters() bool {
	return o != nil && !IsNil(o.Filters)
}

func (o *QueryRequest) SetFilters(v map[string]interface{}) {
	o.Filters = v
}

// Include
func (o *QueryRequest) GetInclude() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Include
}

func (o *QueryRequest) GetIncludeOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Include, true
}

func (o *QueryRequest) SetInclude(v []string) {
	o.Include = v
}

func (o QueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index_name"] = o.IndexName
	toSerialize["index_key"] = o.IndexKey
	if !IsNil(o.QueryVector) {
		toSerialize["query_vector"] = o.QueryVector
	}
	if !IsNil(o.BatchQueryVectors) {
		toSerialize["query_vectors"] = o.BatchQueryVectors // keep wire key
	}
	if !IsNil(o.QueryContents) {
		toSerialize["query_contents"] = o.QueryContents
	}
	toSerialize["top_k"] = o.TopK
	if !IsNil(o.NProbes) {
		toSerialize["n_probes"] = o.NProbes
	}
	if !IsNil(o.Greedy) {
		toSerialize["greedy"] = o.Greedy
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["include"] = o.Include
	return toSerialize, nil
}

func (o *QueryRequest) UnmarshalJSON(data []byte) (err error) {
	// Validate required properties
	requiredProperties := []string{
		"index_name",
		"index_key",
		"top_k",
		"include",
	}

	allProperties := make(map[string]interface{})
	if err = json.Unmarshal(data, &allProperties); err != nil {
		return err
	}
	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	var varQueryRequest _QueryRequest
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&varQueryRequest); err != nil {
		return err
	}

	*o = QueryRequest(varQueryRequest)
	return nil
}

type NullableQueryRequest struct {
	value *QueryRequest
	isSet bool
}

func (v NullableQueryRequest) Get() *QueryRequest {
	return v.value
}

func (v *NullableQueryRequest) Set(val *QueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryRequest(val *QueryRequest) *NullableQueryRequest {
	return &NullableQueryRequest{value: val, isSet: true}
}

func (v NullableQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
