/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ErrorResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorResponseModel{}

// ErrorResponseModel Standard error response model.  Attributes:     status_code (int): HTTP status code of the error.     detail (str): A detailed message describing the error.
type ErrorResponseModel struct {
	StatusCode int32 `json:"status_code"`
	Detail string `json:"detail"`
}

type _ErrorResponseModel ErrorResponseModel

// NewErrorResponseModel instantiates a new ErrorResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorResponseModel(statusCode int32, detail string) *ErrorResponseModel {
	this := ErrorResponseModel{}
	this.StatusCode = statusCode
	this.Detail = detail
	return &this
}

// NewErrorResponseModelWithDefaults instantiates a new ErrorResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorResponseModelWithDefaults() *ErrorResponseModel {
	this := ErrorResponseModel{}
	return &this
}

// GetStatusCode returns the StatusCode field value
func (o *ErrorResponseModel) GetStatusCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
func (o *ErrorResponseModel) GetStatusCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCode, true
}

// SetStatusCode sets field value
func (o *ErrorResponseModel) SetStatusCode(v int32) {
	o.StatusCode = v
}

// GetDetail returns the Detail field value
func (o *ErrorResponseModel) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *ErrorResponseModel) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *ErrorResponseModel) SetDetail(v string) {
	o.Detail = v
}

func (o ErrorResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status_code"] = o.StatusCode
	toSerialize["detail"] = o.Detail
	return toSerialize, nil
}

func (o *ErrorResponseModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status_code",
		"detail",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorResponseModel := _ErrorResponseModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varErrorResponseModel)

	if err != nil {
		return err
	}

	*o = ErrorResponseModel(varErrorResponseModel)

	return err
}

type NullableErrorResponseModel struct {
	value *ErrorResponseModel
	isSet bool
}

func (v NullableErrorResponseModel) Get() *ErrorResponseModel {
	return v.value
}

func (v *NullableErrorResponseModel) Set(val *ErrorResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorResponseModel(val *ErrorResponseModel) *NullableErrorResponseModel {
	return &NullableErrorResponseModel{value: val, isSet: true}
}

func (v NullableErrorResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


