/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.17.1.dev16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
)

// checks if the MetadataFieldPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetadataFieldPolicy{}

// MetadataFieldPolicy Per-field metadata indexing policy (one entry of `metadata_schema`).  Metadata itself stays schemaless — this is indexing policy, not validation.  Fields omitted from `metadata_schema` inherit the index-everything default.  Attributes:     filterable: Build inverted-index postings for the field, so         filters on it resolve from the index (pre-filter).  When         `false`, the field is still stored and still filterable, but         a filter referencing it forces the dense forward-blob         post-filter path — cheaper writes, slower filtered queries.     pattern: Additionally build the field's regex dictionary, which         makes `$regex` / `$contains` resolvable from the index.         Requires `filterable=true`.
type MetadataFieldPolicy struct {
	Filterable *bool `json:"filterable,omitempty"`
	Pattern *bool `json:"pattern,omitempty"`
}

// NewMetadataFieldPolicy instantiates a new MetadataFieldPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataFieldPolicy() *MetadataFieldPolicy {
	this := MetadataFieldPolicy{}
	var filterable bool = true
	this.Filterable = &filterable
	var pattern bool = false
	this.Pattern = &pattern
	return &this
}

// NewMetadataFieldPolicyWithDefaults instantiates a new MetadataFieldPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataFieldPolicyWithDefaults() *MetadataFieldPolicy {
	this := MetadataFieldPolicy{}
	var filterable bool = true
	this.Filterable = &filterable
	var pattern bool = false
	this.Pattern = &pattern
	return &this
}

// GetFilterable returns the Filterable field value if set, zero value otherwise.
func (o *MetadataFieldPolicy) GetFilterable() bool {
	if o == nil || IsNil(o.Filterable) {
		var ret bool
		return ret
	}
	return *o.Filterable
}

// GetFilterableOk returns a tuple with the Filterable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataFieldPolicy) GetFilterableOk() (*bool, bool) {
	if o == nil || IsNil(o.Filterable) {
		return nil, false
	}
	return o.Filterable, true
}

// HasFilterable returns a boolean if a field has been set.
func (o *MetadataFieldPolicy) HasFilterable() bool {
	if o != nil && !IsNil(o.Filterable) {
		return true
	}

	return false
}

// SetFilterable gets a reference to the given bool and assigns it to the Filterable field.
func (o *MetadataFieldPolicy) SetFilterable(v bool) {
	o.Filterable = &v
}

// GetPattern returns the Pattern field value if set, zero value otherwise.
func (o *MetadataFieldPolicy) GetPattern() bool {
	if o == nil || IsNil(o.Pattern) {
		var ret bool
		return ret
	}
	return *o.Pattern
}

// GetPatternOk returns a tuple with the Pattern field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataFieldPolicy) GetPatternOk() (*bool, bool) {
	if o == nil || IsNil(o.Pattern) {
		return nil, false
	}
	return o.Pattern, true
}

// HasPattern returns a boolean if a field has been set.
func (o *MetadataFieldPolicy) HasPattern() bool {
	if o != nil && !IsNil(o.Pattern) {
		return true
	}

	return false
}

// SetPattern gets a reference to the given bool and assigns it to the Pattern field.
func (o *MetadataFieldPolicy) SetPattern(v bool) {
	o.Pattern = &v
}

func (o MetadataFieldPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetadataFieldPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filterable) {
		toSerialize["filterable"] = o.Filterable
	}
	if !IsNil(o.Pattern) {
		toSerialize["pattern"] = o.Pattern
	}
	return toSerialize, nil
}

type NullableMetadataFieldPolicy struct {
	value *MetadataFieldPolicy
	isSet bool
}

func (v NullableMetadataFieldPolicy) Get() *MetadataFieldPolicy {
	return v.value
}

func (v *NullableMetadataFieldPolicy) Set(val *MetadataFieldPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataFieldPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataFieldPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataFieldPolicy(val *MetadataFieldPolicy) *NullableMetadataFieldPolicy {
	return &NullableMetadataFieldPolicy{value: val, isSet: true}
}

func (v NullableMetadataFieldPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataFieldPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


