/*
CyborgDB API

CyborgDB is a secure, encrypted vector database that allows you to store and query high-dimensional vectors with end-to-end encryption. This OpenAPI specification describes the REST interface used by the Go SDK client to perform operations such as indexing, querying, and health checks.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
)

// checks if the GetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetResponse{}

// GetResponse represents the response model for retrieving multiple encrypted index items.
// This model contains the results of a get operation, where each result item
// includes the requested fields (vector, metadata, contents) for the retrieved vectors.
// The response structure allows for efficient batch retrieval of vectors by their IDs.
type GetResponse struct {
	// Results contains a list of retrieved items with the fields that were requested in the get operation.
	// Each item in the results corresponds to a vector that was successfully found in the index.
	// If a requested ID was not found in the index, it will not appear in this results list.
	// The order of results may not necessarily match the order of IDs in the original request.
	Results []GetResultItemModel `json:"results,omitempty"`
}

// NewGetResponse instantiates a new GetResponse object with default values.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
//
// Returns:
//   - *GetResponse: A pointer to the newly created GetResponse instance
func NewGetResponse() *GetResponse {
	this := GetResponse{}
	return &this
}

// NewGetResponseWithDefaults instantiates a new GetResponse object with default values.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set.
//
// Returns:
//   - *GetResponse: A pointer to the newly created GetResponse instance
func NewGetResponseWithDefaults() *GetResponse {
	this := GetResponse{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
// This method retrieves the list of vector items that were successfully retrieved from the index.
//
// Returns:
//   - []GetResultItemModel: Slice of retrieved vector items, or empty slice if not set
func (o *GetResponse) GetResults() []GetResultItemModel {
	if o == nil || IsNil(o.Results) {
		var ret []GetResultItemModel
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
// This method is useful when you need to distinguish between an empty slice and an unset value.
//
// Returns:
//   - []GetResultItemModel: Slice of retrieved vector items
//   - bool: true if the results were set, false otherwise
func (o *GetResponse) GetResultsOk() ([]GetResultItemModel, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults checks if the Results field has been set.
// This method determines whether any results were included in the response.
//
// Returns:
//   - bool: true if results are present, false otherwise
func (o *GetResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}
	return false
}

// SetResults gets a reference to the given []GetResultItemModel and assigns it to the Results field.
// This method sets the list of retrieved vector items in the response.
//
// Parameters:
//   - v: Slice of GetResultItemModel representing the retrieved vectors
func (o *GetResponse) SetResults(v []GetResultItemModel) {
	o.Results = v
}

// GetResultCount returns the number of results in the response.
// This is a convenience method to quickly determine how many vectors were retrieved.
//
// Returns:
//   - int: The number of retrieved vector items
func (o *GetResponse) GetResultCount() int {
	if o == nil || o.Results == nil {
		return 0
	}
	return len(o.Results)
}

// GetResultByID finds a result item by its ID.
// This method searches through the results to find a vector with the specified ID.
//
// Parameters:
//   - id: The unique identifier of the vector to find
//
// Returns:
//   - *GetResultItemModel: Pointer to the found result item, or nil if not found
//   - bool: true if the item was found, false otherwise
//
// Example:
//   if result, found := response.GetResultByID("vector-123"); found {
//       fmt.Printf("Found vector: %s\n", result.GetId())
//   }
func (o *GetResponse) GetResultByID(id string) (*GetResultItemModel, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	
	for i := range o.Results {
		if o.Results[i].GetId() == id {
			return &o.Results[i], true
		}
	}
	return nil, false
}

// GetAllIDs returns all vector IDs from the response results.
// This is a convenience method to extract just the IDs of all retrieved vectors.
//
// Returns:
//   - []string: Slice of all vector IDs in the results
//
// Example:
//   ids := response.GetAllIDs()
//   fmt.Printf("Retrieved %d vectors with IDs: %v\n", len(ids), ids)
func (o *GetResponse) GetAllIDs() []string {
	if o == nil || o.Results == nil {
		return nil
	}
	
	ids := make([]string, len(o.Results))
	for i, result := range o.Results {
		ids[i] = result.GetId()
	}
	return ids
}

// MarshalJSON converts the GetResponse to JSON format.
// This method serializes the GetResponse struct into a JSON byte array suitable for API transmission.
//
// Returns:
//   - []byte: The JSON representation of the GetResponse
//   - error: Any error that occurred during marshaling
func (o GetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

// ToMap converts the GetResponse to a map representation suitable for JSON serialization.
// This method creates a map containing all the fields of the GetResponse.
//
// Returns:
//   - map[string]interface{}: A map containing the serializable fields
//   - error: Any error that occurred during conversion (currently always nil)
func (o GetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

// NullableGetResponse is a wrapper that allows GetResponse to be nullable.
// It tracks whether the value has been explicitly set, which is useful for API serialization
// where you need to distinguish between a zero value and an explicitly set value.
type NullableGetResponse struct {
	value *GetResponse
	isSet bool
}

// Get retrieves the underlying GetResponse value.
//
// Returns:
//   - *GetResponse: The wrapped GetResponse value, or nil if not set
func (v NullableGetResponse) Get() *GetResponse {
	return v.value
}

// Set assigns a new GetResponse value and marks it as set.
//
// Parameters:
//   - val: The GetResponse value to set
func (v *NullableGetResponse) Set(val *GetResponse) {
	v.value = val
	v.isSet = true
}

// IsSet checks whether a value has been explicitly set.
//
// Returns:
//   - bool: true if a value has been set, false otherwise
func (v NullableGetResponse) IsSet() bool {
	return v.isSet
}

// Unset clears the value and marks it as not set.
func (v *NullableGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

// NewNullableGetResponse creates a new NullableGetResponse with the given value.
//
// Parameters:
//   - val: The GetResponse value to wrap
//
// Returns:
//   - *NullableGetResponse: A new NullableGetResponse instance
func NewNullableGetResponse(val *GetResponse) *NullableGetResponse {
	return &NullableGetResponse{value: val, isSet: true}
}

// MarshalJSON converts the NullableGetResponse to JSON format.
//
// Returns:
//   - []byte: The JSON representation of the wrapped value
//   - error: Any error that occurred during marshaling
func (v NullableGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

// UnmarshalJSON deserializes JSON data into the NullableGetResponse.
//
// Parameters:
//   - src: The JSON data to unmarshal
//
// Returns:
//   - error: Any error that occurred during unmarshaling
func (v *NullableGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// ============================================================================
// GetResultItemModel - Individual result item within GetResponse
// ============================================================================

// checks if the GetResultItemModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetResultItemModel{}

// GetResultItemModel represents an individual result item containing the retrieved vector data.
// This model represents a single vector item returned from a get operation,
// containing the ID and optionally the vector, metadata, and contents based on the include parameter.
// The presence of each field depends on what was requested in the original get request.
type GetResultItemModel struct {
	// Id is the unique identifier of the vector item.
	// This field is always present and matches the ID that was used when the vector was originally upserted.
	Id string `json:"id"`
	
	// Vector contains the high-dimensional vector data as an array of float32 values.
	// This field is included only if "vector" was specified in the include parameter of the get request.
	// For IVFPQ indexes, the returned vector may be compressed and have different dimensions than the original.
	Vector []float32 `json:"vector,omitempty"`
	
	// Metadata contains additional structured data associated with the vector.
	// This field is included only if "metadata" was specified in the include parameter of the get request.
	// The metadata can contain arbitrary key-value pairs that were stored with the vector.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	
	// Contents contains text or binary content associated with the vector.
	// This field is included only if "contents" was specified in the include parameter of the get request.
	// The content is stored as a string and may represent text data or base64-encoded binary data.
	Contents *string `json:"contents,omitempty"`
}

// NewGetResultItemModel instantiates a new GetResultItemModel object with the required ID.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set.
//
// Parameters:
//   - id: The unique identifier of the vector item
//
// Returns:
//   - *GetResultItemModel: A pointer to the newly created GetResultItemModel instance
func NewGetResultItemModel(id string) *GetResultItemModel {
	this := GetResultItemModel{}
	this.Id = id
	return &this
}

// NewGetResultItemModelWithDefaults instantiates a new GetResultItemModel object with default values.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set.
//
// Returns:
//   - *GetResultItemModel: A pointer to the newly created GetResultItemModel instance
func NewGetResultItemModelWithDefaults() *GetResultItemModel {
	this := GetResultItemModel{}
	return &this
}

// GetId returns the Id field value.
// This method retrieves the unique identifier of the vector item.
//
// Returns:
//   - string: The vector ID
func (o *GetResultItemModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.Id
}

// GetIdOk returns a tuple with the Id field value and a boolean indicating if the value was set.
//
// Returns:
//   - *string: Pointer to the vector ID
//   - bool: true if the ID was set, false otherwise
func (o *GetResultItemModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets the Id field value.
// This method assigns the unique identifier for the vector item.
//
// Parameters:
//   - v: The vector ID to set
func (o *GetResultItemModel) SetId(v string) {
	o.Id = v
}

// GetVector returns the Vector field value if set, zero value otherwise.
// This method retrieves the high-dimensional vector data.
//
// Returns:
//   - []float32: The vector data, or empty slice if not set
func (o *GetResultItemModel) GetVector() []float32 {
	if o == nil || IsNil(o.Vector) {
		var ret []float32
		return ret
	}
	return o.Vector
}

// GetVectorOk returns a tuple with the Vector field value if set, nil otherwise
// and a boolean to check if the value has been set.
//
// Returns:
//   - []float32: The vector data
//   - bool: true if the vector was set, false otherwise
func (o *GetResultItemModel) GetVectorOk() ([]float32, bool) {
	if o == nil || IsNil(o.Vector) {
		return nil, false
	}
	return o.Vector, true
}

// HasVector checks if the Vector field has been set.
// This method determines whether vector data was included in the response.
//
// Returns:
//   - bool: true if vector data is present, false otherwise
func (o *GetResultItemModel) HasVector() bool {
	if o != nil && !IsNil(o.Vector) {
		return true
	}
	return false
}

// SetVector gets a reference to the given []float32 and assigns it to the Vector field.
// This method sets the high-dimensional vector data.
//
// Parameters:
//   - v: The vector data to set
func (o *GetResultItemModel) SetVector(v []float32) {
	o.Vector = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
// This method retrieves the structured metadata associated with the vector.
//
// Returns:
//   - map[string]interface{}: The metadata key-value pairs, or empty map if not set
func (o *GetResultItemModel) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
//
// Returns:
//   - map[string]interface{}: The metadata key-value pairs
//   - bool: true if metadata was set, false otherwise
func (o *GetResultItemModel) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata checks if the Metadata field has been set.
// This method determines whether metadata was included in the response.
//
// Returns:
//   - bool: true if metadata is present, false otherwise
func (o *GetResultItemModel) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}
	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
// This method sets the structured metadata for the vector.
//
// Parameters:
//   - v: The metadata key-value pairs to set
func (o *GetResultItemModel) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetContents returns the Contents field value if set, zero value otherwise.
// This method retrieves the text or binary content associated with the vector.
//
// Returns:
//   - string: The content data, or empty string if not set
func (o *GetResultItemModel) GetContents() string {
	if o == nil || IsNil(o.Contents) {
		var ret string
		return ret
	}
	return *o.Contents
}

// GetContentsOk returns a tuple with the Contents field value if set, nil otherwise
// and a boolean to check if the value has been set.
//
// Returns:
//   - *string: Pointer to the content data
//   - bool: true if contents were set, false otherwise
func (o *GetResultItemModel) GetContentsOk() (*string, bool) {
	if o == nil || IsNil(o.Contents) {
		return nil, false
	}
	return o.Contents, true
}

// HasContents checks if the Contents field has been set.
// This method determines whether content data was included in the response.
//
// Returns:
//   - bool: true if contents are present, false otherwise
func (o *GetResultItemModel) HasContents() bool {
	if o != nil && !IsNil(o.Contents) {
		return true
	}
	return false
}

// SetContents gets a reference to the given string and assigns it to the Contents field.
// This method sets the text or binary content for the vector.
//
// Parameters:
//   - v: The content data to set
func (o *GetResultItemModel) SetContents(v string) {
	o.Contents = &v
}

// GetVectorDimension returns the dimension of the vector (0 if no vector).
// This is a convenience method to quickly determine the dimensionality of the vector data.
//
// Returns:
//   - int: The number of dimensions in the vector, or 0 if no vector data is present
func (o *GetResultItemModel) GetVectorDimension() int {
	if o == nil || o.Vector == nil {
		return 0
	}
	return len(o.Vector)
}

// GetMetadataValue safely retrieves a specific metadata value by key.
// This method provides a safe way to access metadata values without risking nil pointer dereferences.
//
// Parameters:
//   - key: The metadata key to retrieve
//
// Returns:
//   - interface{}: The metadata value, or nil if the key doesn't exist
//   - bool: true if the key exists in the metadata, false otherwise
//
// Example:
//   if value, exists := item.GetMetadataValue("category"); exists {
//       fmt.Printf("Category: %v\n", value)
//   }
func (o *GetResultItemModel) GetMetadataValue(key string) (interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	value, exists := o.Metadata[key]
	return value, exists
}

// MarshalJSON converts the GetResultItemModel to JSON format.
//
// Returns:
//   - []byte: The JSON representation of the GetResultItemModel
//   - error: Any error that occurred during marshaling
func (o GetResultItemModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

// ToMap converts the GetResultItemModel to a map representation suitable for JSON serialization.
//
// Returns:
//   - map[string]interface{}: A map containing the serializable fields
//   - error: Any error that occurred during conversion (currently always nil)
func (o GetResultItemModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Vector) {
		toSerialize["vector"] = o.Vector
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Contents) {
		toSerialize["contents"] = o.Contents
	}
	return toSerialize, nil
}

// NullableGetResultItemModel wrapper for nullable GetResultItemModel
type NullableGetResultItemModel struct {
	value *GetResultItemModel
	isSet bool
}

// Get retrieves the underlying GetResultItemModel value.
func (v NullableGetResultItemModel) Get() *GetResultItemModel {
	return v.value
}

// Set assigns a new GetResultItemModel value and marks it as set.
func (v *NullableGetResultItemModel) Set(val *GetResultItemModel) {
	v.value = val
	v.isSet = true
}

// IsSet checks whether a value has been explicitly set.
func (v NullableGetResultItemModel) IsSet() bool {
	return v.isSet
}

// Unset clears the value and marks it as not set.
func (v *NullableGetResultItemModel) Unset() {
	v.value = nil
	v.isSet = false
}

// NewNullableGetResultItemModel creates a new NullableGetResultItemModel with the given value.
func NewNullableGetResultItemModel(val *GetResultItemModel) *NullableGetResultItemModel {
	return &NullableGetResultItemModel{value: val, isSet: true}
}

// MarshalJSON converts the NullableGetResultItemModel to JSON format.
func (v NullableGetResultItemModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

// UnmarshalJSON deserializes JSON data into the NullableGetResultItemModel.
func (v *NullableGetResultItemModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}