// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"fmt"
	"bytes"
)

// IndexIVFFlatModel struct for configuring an IVFFlat (Inverted File with Flat quantization) index.
type IndexIVFFlatModel struct {
	Dimension int32  `json:"dimension,omitempty"`
	NLists    int32   `json:"n_lists"`
	Metric    string `json:"metric,omitempty"`
	Type      string  `json:"type"` // default: "ivfflat"
}

type _IndexIVFFlatModel IndexIVFFlatModel

// NewIndexIVFFlatModel creates a new IVFFlat index model with required fields.
func NewIndexIVFFlatModel(dimension int32, metric string, nLists int32) *IndexIVFFlatModel {
	return &IndexIVFFlatModel{
		Dimension: dimension,
		Metric:    metric,
		NLists:    nLists,
		Type:      "ivfflat",
	}
}

// NewIndexIVFFlatModelWithDefaults creates a new IVFFlat index model with default type set.
func NewIndexIVFFlatModelWithDefaults() *IndexIVFFlatModel {
	return &IndexIVFFlatModel{
		Type: "ivfflat",
	}
}

func (o IndexIVFFlatModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return nil, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexIVFFlatModel) ToMap() (map[string]interface{}, error) {
	return map[string]interface{}{
		"dimension": o.Dimension,
		"n_lists":   o.NLists,
		"metric":    o.Metric,
		"type":      o.Type,
	}, nil
}

func (o *IndexIVFFlatModel) UnmarshalJSON(data []byte) error {
	requiredProps := []string{"dimension", "metric", "n_lists"}
	var allProps map[string]interface{}
	err := json.Unmarshal(data, &allProps)
	if err != nil {
		return err
	}
	for _, prop := range requiredProps {
		if _, found := allProps[prop]; !found {
			return fmt.Errorf("required field %s is missing", prop)
		}
	}

	var temp _IndexIVFFlatModel
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&temp)
	if err != nil {
		return err
	}

	*o = IndexIVFFlatModel(temp)

	if o.Type == "" {
		o.Type = "ivfflat"
	}
	return nil
}

type NullableIndexIVFFlatModel struct {
	value *IndexIVFFlatModel
	isSet bool
}

func (v NullableIndexIVFFlatModel) Get() *IndexIVFFlatModel {
	return v.value
}

func (v *NullableIndexIVFFlatModel) Set(val *IndexIVFFlatModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexIVFFlatModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexIVFFlatModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexIVFFlatModel(val *IndexIVFFlatModel) *NullableIndexIVFFlatModel {
	return &NullableIndexIVFFlatModel{value: val, isSet: true}
}

func (v NullableIndexIVFFlatModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexIVFFlatModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (m *IndexIVFFlatModel) isIndexModel() {}