/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetResponseModel{}

// GetResponseModel Response model for retrieving multiple encrypted index items.  Attributes:     results (List[GetResultItem]): A list of retrieved items with requested fields.
type GetResponseModel struct {
	Results []GetResultItemModel `json:"results"`
}

type _GetResponseModel GetResponseModel

// NewGetResponseModel instantiates a new GetResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetResponseModel(results []GetResultItemModel) *GetResponseModel {
	this := GetResponseModel{}
	this.Results = results
	return &this
}

// NewGetResponseModelWithDefaults instantiates a new GetResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetResponseModelWithDefaults() *GetResponseModel {
	this := GetResponseModel{}
	return &this
}

// GetResults returns the Results field value
func (o *GetResponseModel) GetResults() []GetResultItemModel {
	if o == nil {
		var ret []GetResultItemModel
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *GetResponseModel) GetResultsOk() ([]GetResultItemModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *GetResponseModel) SetResults(v []GetResultItemModel) {
	o.Results = v
}

func (o GetResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *GetResponseModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetResponseModel := _GetResponseModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetResponseModel)

	if err != nil {
		return err
	}

	*o = GetResponseModel(varGetResponseModel)

	return err
}

type NullableGetResponseModel struct {
	value *GetResponseModel
	isSet bool
}

func (v NullableGetResponseModel) Get() *GetResponseModel {
	return v.value
}

func (v *NullableGetResponseModel) Set(val *GetResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGetResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGetResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetResponseModel(val *GetResponseModel) *NullableGetResponseModel {
	return &NullableGetResponseModel{value: val, isSet: true}
}

func (v NullableGetResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


