/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.16.3.dev154
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRequest{}

// GetRequest Request model for retrieving specific vectors from the index.  Inherits:     IndexOperationRequest: Includes `index_name` and `index_key`.  Attributes:     ids (List[str]): List of vector item IDs to retrieve.     include (List[str]): List of fields to include in the response.         Defaults to `[\"vector\", \"contents\", \"metadata\"]`.
type GetRequest struct {
	Ids []string `json:"ids"`
	Include []string `json:"include,omitempty"`
	// 32-byte encryption key as hex string.  Required for SDK-supplied indexes; must be omitted for KMS-backed indexes (the service resolves the KEK via the index's KMSBlob).
	IndexKey NullableString `json:"index_key,omitempty"`
	// ID name
	IndexName string `json:"index_name"`
}

type _GetRequest GetRequest

// NewGetRequest instantiates a new GetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRequest(ids []string, indexName string) *GetRequest {
	this := GetRequest{}
	this.Ids = ids
	this.IndexName = indexName
	return &this
}

// NewGetRequestWithDefaults instantiates a new GetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRequestWithDefaults() *GetRequest {
	this := GetRequest{}
	return &this
}

// GetIds returns the Ids field value
func (o *GetRequest) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *GetRequest) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *GetRequest) SetIds(v []string) {
	o.Ids = v
}

// GetInclude returns the Include field value if set, zero value otherwise.
func (o *GetRequest) GetInclude() []string {
	if o == nil || IsNil(o.Include) {
		var ret []string
		return ret
	}
	return o.Include
}

// GetIncludeOk returns a tuple with the Include field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequest) GetIncludeOk() ([]string, bool) {
	if o == nil || IsNil(o.Include) {
		return nil, false
	}
	return o.Include, true
}

// HasInclude returns a boolean if a field has been set.
func (o *GetRequest) HasInclude() bool {
	if o != nil && !IsNil(o.Include) {
		return true
	}

	return false
}

// SetInclude gets a reference to the given []string and assigns it to the Include field.
func (o *GetRequest) SetInclude(v []string) {
	o.Include = v
}

// GetIndexKey returns the IndexKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRequest) GetIndexKey() string {
	if o == nil || IsNil(o.IndexKey.Get()) {
		var ret string
		return ret
	}
	return *o.IndexKey.Get()
}

// GetIndexKeyOk returns a tuple with the IndexKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRequest) GetIndexKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IndexKey.Get(), o.IndexKey.IsSet()
}

// HasIndexKey returns a boolean if a field has been set.
func (o *GetRequest) HasIndexKey() bool {
	if o != nil && o.IndexKey.IsSet() {
		return true
	}

	return false
}

// SetIndexKey gets a reference to the given NullableString and assigns it to the IndexKey field.
func (o *GetRequest) SetIndexKey(v string) {
	o.IndexKey.Set(&v)
}
// SetIndexKeyNil sets the value for IndexKey to be an explicit nil
func (o *GetRequest) SetIndexKeyNil() {
	o.IndexKey.Set(nil)
}

// UnsetIndexKey ensures that no value is present for IndexKey, not even an explicit nil
func (o *GetRequest) UnsetIndexKey() {
	o.IndexKey.Unset()
}

// GetIndexName returns the IndexName field value
func (o *GetRequest) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *GetRequest) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *GetRequest) SetIndexName(v string) {
	o.IndexName = v
}

func (o GetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ids"] = o.Ids
	if !IsNil(o.Include) {
		toSerialize["include"] = o.Include
	}
	if o.IndexKey.IsSet() {
		toSerialize["index_key"] = o.IndexKey.Get()
	}
	toSerialize["index_name"] = o.IndexName
	return toSerialize, nil
}

func (o *GetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ids",
		"index_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRequest := _GetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	
	err = decoder.Decode(&varGetRequest)

	if err != nil {
		return err
	}

	*o = GetRequest(varGetRequest)

	return err
}

type NullableGetRequest struct {
	value *GetRequest
	isSet bool
}

func (v NullableGetRequest) Get() *GetRequest {
	return v.value
}

func (v *NullableGetRequest) Set(val *GetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRequest(val *GetRequest) *NullableGetRequest {
	return &NullableGetRequest{value: val, isSet: true}
}

func (v NullableGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


