/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteRequest{}

// DeleteRequest Request model for deleting vectors from the encrypted index.  Inherits:     IndexOperationRequest: Includes `index_name` and `index_key`.  Attributes:     ids (List[str]): List of vector item IDs to be deleted.
type DeleteRequest struct {
	// 32-byte encryption key as hex string
	IndexKey string `json:"index_key"`
	// ID name
	IndexName string `json:"index_name"`
	Ids []string `json:"ids"`
}

type _DeleteRequest DeleteRequest

// NewDeleteRequest instantiates a new DeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteRequest(indexKey string, indexName string, ids []string) *DeleteRequest {
	this := DeleteRequest{}
	this.IndexKey = indexKey
	this.IndexName = indexName
	this.Ids = ids
	return &this
}

// NewDeleteRequestWithDefaults instantiates a new DeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteRequestWithDefaults() *DeleteRequest {
	this := DeleteRequest{}
	return &this
}

// GetIndexKey returns the IndexKey field value
func (o *DeleteRequest) GetIndexKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexKey
}

// GetIndexKeyOk returns a tuple with the IndexKey field value
// and a boolean to check if the value has been set.
func (o *DeleteRequest) GetIndexKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexKey, true
}

// SetIndexKey sets field value
func (o *DeleteRequest) SetIndexKey(v string) {
	o.IndexKey = v
}

// GetIndexName returns the IndexName field value
func (o *DeleteRequest) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *DeleteRequest) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *DeleteRequest) SetIndexName(v string) {
	o.IndexName = v
}

// GetIds returns the Ids field value
func (o *DeleteRequest) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *DeleteRequest) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *DeleteRequest) SetIds(v []string) {
	o.Ids = v
}

func (o DeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index_key"] = o.IndexKey
	toSerialize["index_name"] = o.IndexName
	toSerialize["ids"] = o.Ids
	return toSerialize, nil
}

func (o *DeleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index_key",
		"index_name",
		"ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteRequest := _DeleteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteRequest)

	if err != nil {
		return err
	}

	*o = DeleteRequest(varDeleteRequest)

	return err
}

type NullableDeleteRequest struct {
	value *DeleteRequest
	isSet bool
}

func (v NullableDeleteRequest) Get() *DeleteRequest {
	return v.value
}

func (v *NullableDeleteRequest) Set(val *DeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteRequest(val *DeleteRequest) *NullableDeleteRequest {
	return &NullableDeleteRequest{value: val, isSet: true}
}

func (v NullableDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


