/*
CyborgDB Service

REST API for CyborgDB: The Confidential Vector Database

API version: 0.17.1.dev16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueryMetadataResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryMetadataResponse{}

// QueryMetadataResponse Response model for a metadata query.  Attributes:     results (List[MetadataResult]): Matching items, using core's row shape         directly. On a `text=...` query each row is `{id, score}` in         descending score order; on a filter-only query each row is `{id}`         (no `score` key — there is nothing to score) following `order_by`         when set, else an unordered subset.     ids (List[str]): Matching item IDs, parallel to `results`. Retained         for backward compatibility with callers that only read IDs.     count (int): Number of items returned.
type QueryMetadataResponse struct {
	Results []MetadataResult `json:"results,omitempty"`
	Ids []string `json:"ids"`
	Count int32 `json:"count"`
}

type _QueryMetadataResponse QueryMetadataResponse

// NewQueryMetadataResponse instantiates a new QueryMetadataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryMetadataResponse(ids []string, count int32) *QueryMetadataResponse {
	this := QueryMetadataResponse{}
	this.Ids = ids
	this.Count = count
	return &this
}

// NewQueryMetadataResponseWithDefaults instantiates a new QueryMetadataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryMetadataResponseWithDefaults() *QueryMetadataResponse {
	this := QueryMetadataResponse{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *QueryMetadataResponse) GetResults() []MetadataResult {
	if o == nil || IsNil(o.Results) {
		var ret []MetadataResult
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryMetadataResponse) GetResultsOk() ([]MetadataResult, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *QueryMetadataResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []MetadataResult and assigns it to the Results field.
func (o *QueryMetadataResponse) SetResults(v []MetadataResult) {
	o.Results = v
}

// GetIds returns the Ids field value
func (o *QueryMetadataResponse) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *QueryMetadataResponse) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *QueryMetadataResponse) SetIds(v []string) {
	o.Ids = v
}

// GetCount returns the Count field value
func (o *QueryMetadataResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *QueryMetadataResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *QueryMetadataResponse) SetCount(v int32) {
	o.Count = v
}

func (o QueryMetadataResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryMetadataResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	toSerialize["ids"] = o.Ids
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *QueryMetadataResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ids",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryMetadataResponse := _QueryMetadataResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	
	err = decoder.Decode(&varQueryMetadataResponse)

	if err != nil {
		return err
	}

	*o = QueryMetadataResponse(varQueryMetadataResponse)

	return err
}

type NullableQueryMetadataResponse struct {
	value *QueryMetadataResponse
	isSet bool
}

func (v NullableQueryMetadataResponse) Get() *QueryMetadataResponse {
	return v.value
}

func (v *NullableQueryMetadataResponse) Set(val *QueryMetadataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryMetadataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryMetadataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryMetadataResponse(val *QueryMetadataResponse) *NullableQueryMetadataResponse {
	return &NullableQueryMetadataResponse{value: val, isSet: true}
}

func (v NullableQueryMetadataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryMetadataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


